/* ── CAMPAÑA: eventos ── */

module.exports = [
  { id:'evt-mina-zafira', title:'Llegada a Mina Zafira', status:'done', session:'1',
    description:'Los jugadores despiertan en un barco acercándose lentamente a Mina Zafira. La ciudad debe sentirse viva, misteriosa y abrumadora. Mercaderes, marineros, comida, armaduras y magia llenan las calles. Los jugadores descubren sus habilidades naturalmente mediante el rol.' },
  { id:'evt-zyren-gato', title:'Primer encuentro con Zyren (gato)', status:'done', session:'1',
    description:'Los jugadores notan un gato blanco y negro observándolos cuidadosamente. Si muestran amabilidad, Zyren comienza a confiar en ellos.' },
  { id:'evt-lobo-corrupto', title:'Encuentro con el Lobo Corrupto', status:'done', session:'1',
    description:'En el bosque, los jugadores encuentran un lobo corrupto lleno de energía Fell. Sus ojos y venas brillan verde. El lobo es demasiado fuerte; Zyren revela su verdadera forma y salva al grupo.' },
  { id:'evt-dialogos-zyren', title:'Diálogos importantes de Zyren', status:'done', session:'1',
    description:'"Bienvenidos a Ardaetheros — la tierra donde el cielo y la tierra se unen." · "La confianza se gana paso a paso." · "Una sombra se alza… pero aún no están listos para escuchar su nombre."' },
  { id:'evt-regreso-mina', title:'Regreso a Mina Zafira (compras)', status:'done', session:'1',
    description:'Tras el encuentro con el lobo, Zyren recomienda volver a la ciudad. Reciben monedas de plata para comprar equipo básico. La progresión del poder debe sentirse ganada y natural.' },
  { id:'evt-arana-madre', title:'Encuentro con la Araña Madre Corrupta', status:'done', session:'1',
    description:'Perdidos en el bosque, encuentran una gigantesca araña madre corrupta y varias crías. La pelea pone a prueba la preparación del grupo.' },
  { id:'evt-aparicion-nira', title:'Aparición de Nira', status:'done', session:'1',
    description:'Después de la batalla contra las arañas, Nira aparece primero como pantera sombría. Los jugadores creen que puede estar corrupta. Finalmente revela su verdadera forma y guía al grupo.' },
  { id:'evt-aether-grove', title:'Llegada a Aether Grove', status:'planned', session:'2', order:1000,
    description:'El grupo llega al Grove siguiendo a Nira. Primera impresión del santuario — puentes elevados, plataformas entre árboles ancestrales, luz filtrada. Construido en lo alto, oculto, elegante.' },

  // ── SESIÓN 2 — CONFIRMADO ──
  { id:'evt-isis-pozo', title:'Encuentro con Isis (cerca del pozo)', status:'planned', session:'2', order:1001,
    description:'El grupo ve a Isis de lejos cerca del pozo de agua, completamente en paz. Escena visualmente tranquila y misteriosa. Solo Boyd puede acercarse. Isis menciona algo sobre el origen de los Owling en la otra parte del mundo — solo a Boyd, solo una vez. Lo que sigue queda como semilla para descifrar.' },
  { id:'evt-zael-dormido', title:'Encuentro con Zael (dormido)', status:'planned', session:'2', order:1002,
    description:'El grupo encuentra a Zael probablemente dormido en alguna plataforma. Primera impresión cómica. Zyren lo presenta brevemente. Zael habla en frases cortas. Relyo siente algo familiar con él que ninguno sabría explicar.' },
  { id:'evt-nira-sanacion-boyd', title:'Nira enseña a Boyd magia de sanación', status:'planned', session:'2', order:1003,
    description:'Primeras bases de sanación con magia de naturaleza. Conexión personal que define la relación Boyd-Nira. Punto de inflexión para el druida del grupo.' },
  { id:'evt-sakura-aparece', title:'Sakura aparece — primera mención Sunbound', status:'planned', session:'2', order:1004,
    description:'Sakura llega a Aether Grove con su bolsa de hierbas y frascos. Ve el tatuaje de Ati de Rac y pregunta sin vergüenza — momento de gracia para Rac. Primera mención de los Sunbound Druids para el grupo. Vende a ambas facciones (Velo Elmyra y Sunbound).' },
  { id:'evt-subida-nivel-3', title:'Subida a Nivel 3 — Zyren los reúne', status:'planned', session:'2', order:1005,
    description:'Zyren reúne al grupo después de las interacciones en el Grove. Les dice que lo que vivieron en el bosque los cambió. Nivel 3 desbloqueado narrativamente.\n\nHP nivel 3:\n• Rac: 27 · Tyrell: 21 · Relyo: 16 · Boyd: 15 · Esdas: 12' },
  { id:'evt-mision-zyren-solmira', title:'Misión de Zyren: ir a Solmira', status:'planned', session:'2', order:1006,
    description:'Zyren les da la misión: ir a Solmira y contactar a los Sunbound Druids. Pedir hablar con su líder. Primera vez que el grupo tiene un objetivo claro fuera del bosque.' },
  { id:'evt-sirvientes-fell', title:'Encuentro 3 — Sirvientes del Fell Lord', status:'planned', session:'2', order:1007,
    description:'Saliendo del Bosque Eldenmyr, camino al Valle Aethon. Composición: 2 Guerreros Corruptos + 1 Pícaro Fell + 2 Arqueros Corruptos + Comandante Fell (enfrenta Zyren solo).\n\nZyren se aleja con el Comandante. Nira maneja 1-2 enemigos. El grupo enfrenta el resto. Si el pícaro baja a Esdas o Boyd a menos de 5 HP en turno 3 → Nira interviene.' },
  { id:'evt-revelacion-comandante', title:'Revelación post-combate: insignia del Fell Lord', status:'planned', session:'2', order:1008,
    description:'Zyren examina el cuerpo del Comandante:\n1. Era soldado de la Capital — su armadura lo delata.\n2. La corrupción lo transformó físicamente — más grande, casi sin alma.\n3. "Eso les podría haber pasado" — mira a Rac y Esdas.\n\nMuestra la INSIGNIA DEL FELL LORD: círculo de hierro verde oscuro con líneas interlazadas y mini círculos. La copia en un scroll con un hechizo mínimo de fuego. Se lo entrega a Esdas: "Es un hechizo simple. Ustedes dos pueden hacerlo si concentran su energía correctamente." (mirando a Boyd y Esdas)' },
  { id:'evt-zyren-nira-se-van', title:'Zyren y Nira vuelven al Grove', status:'planned', session:'2', order:1009,
    description:'"Por ahora no podré acompañarlos hacia Solmira. Nira y yo tenemos que volver al Grove y ver con Isis si hay manera de salvar cuerpos ya corrompidos por el Fell."\n\n"Si no llego antes de que necesiten ayuda, mandaré a Zael."\n\nDesaparecen entre los árboles. El grupo está SOLO por primera vez en la campaña.' },
  { id:'evt-bandidos-camino', title:'Encuentro 5 — Bandidos del camino', status:'planned', session:'2', order:1010,
    description:'Camino abierto del Valle Aethon hacia Solmira. 4 Bandidos Comunes + 1 Líder. ENCUENTRO MORAL — primer enemigo que no es monstruo ni Fell.\n\nLa decisión del grupo afecta DIRECTAMENTE la relación con Pip y Mila en Solmira:\n• Si los matan: relación fría/hostil\n• Si los dejan huir: relación abierta\n• Si son generosos o ayudan: confianza rápida\n\nInfo disponible si hablan: vienen de una aldea al norte del Valle Aethon. Algo Fell atacó su aldea hace 3 meses (hilo Fell sin confirmar).' },
  { id:'evt-llegada-solmira', title:'Llegada a Solmira', status:'planned', session:'2', order:1011,
    description:'El grupo llega a la ciudad. Primeras impresiones del mercado ordenado, el Hall de los Sunbound, la sede de la Escuela de Magos. Solmira es más académica y ordenada que Mina Zafira.' },

  // ── SESIÓN 3 — CONFIRMADO PARCIALMENTE ──
  { id:'evt-barek-cara-amigable', title:'Encuentro con Barek (Sunbound)', status:'planned', session:'3', order:1012,
    description:'Primera cara amigable Sunbound. Barek genuinamente bueno, sin fachada. A través de él el grupo llega a Sura.' },
  { id:'evt-sura-fell-lord', title:'Sura habla del Fell Lord sin evasivas', status:'planned', session:'3', order:1013,
    description:'Sura es la primera figura que habla del Fell Lord directamente. Da al grupo el contexto real de lo que está pasando en Ardaetheros. Reacción al ver la insignia Fell — probablemente la reconoce o tiene información parcial. Relyo siente algo familiar en ella.' },
  { id:'evt-aela-precio-info', title:'Encuentro con Aela (informante)', status:'planned', session:'3', order:1014,
    description:'Informante. Si el grupo muestra la insignia Fell, Aela quiere algo a cambio de la información. El precio depende de qué sabe exactamente. Aela puede reconocer a Tyrell de alguna manera al verlo (contexto a definir). Sistema de precios: dinero, favores o algo personal.' },
  { id:'evt-pip-mila', title:'Encuentro con Pip y Mila', status:'planned', session:'3', order:1015,
    description:'La relación inicial depende COMPLETAMENTE de la decisión con los bandidos en el camino. Pip = espejo del pasado de Tyrell (abandonado, calles). Mila solo se acerca a Boyd — le fascinan sus plumas de Owling.' },
  { id:'evt-caeron-frio', title:'Encuentro con Caeron (Alcalde)', status:'planned', session:'3', order:1016,
    description:'Actitud inicial fría y discriminatoria. El Alcalde desconfía del grupo pero respeta a Sura. Actitud diferenciada por personaje: Rac (desconfianza), Relyo/Esdas (respeto frío por ser elfos), Tyrell y Boyd (incomodidad por raza desconocida).' },
  { id:'evt-escuela-magos', title:'Esdas descubre la Escuela de Magos', status:'planned', session:'3', order:1017,
    description:'Primer contacto del grupo con el mundo académico arcano. Esdas descubre que existe una institución formal de magia, con sede también en la Capital. Posible hilo de evolución arcana orgánica para Esdas.' },
  { id:'evt-ataque-solmira', title:'Encuentro 4 — Ataque a Solmira', status:'planned', session:'3', order:1018,
    description:'Más soldados Fell que el Encuentro 3 + Hienas Corruptas Fell + Comandante nuevo (inferior al del Encuentro 3).\n\nEl momento decisivo: ¿el grupo defiende la ciudad?\n\nSi defienden:\n• Caeron los ve en acción por primera vez\n• El muro de su prejuicio se rompe\n• Abre puertas políticas en Solmira\n• Alianza formal con los Sunbound\n• Información más completa sobre el Fell Lord' }
];
