/* ── CAMPAÑA: hilos narrativos ── */

module.exports = [
  // ── HILOS PRINCIPALES ──
  { id:'thread-despertar', name:'El Despertar en Ardaetheros', status:'active',
    description:'Los héroes llegaron al mundo sin saber por qué. Zyren los reconoció. Zyren mencionó "una resonancia" al sentirlos. Hay una razón detrás de su presencia que aún no se revela.',
    characters:['Zyren','Rac','Relyo','Tyrell','Boyd','Esdas'] },
  { id:'thread-resonancia', name:'La "Resonancia" — qué significa exactamente', status:'active',
    description:'Zyren la mencionó al sentir al grupo: "Cuando entraron en Ardaetheros, sentí una resonancia." Es probablemente parte de la verdad oculta sobre por qué fueron transportados al mundo. Conectada con el equilibrio del mundo.',
    characters:['Zyren'] },
  { id:'thread-fell', name:'La Corrupción Fell', status:'active',
    description:'Energía verde orgánica que controla, distorsiona y transforma criaturas vivas sin destruir su esencia. Aparece en bestias, monstruos y humanoides. Insignia Fell descubierta: círculo de hierro verde oscuro con líneas interlazadas y mini círculos. Posible economía propia (monedas con símbolo desconocido).',
    characters:['Lobo Corrupto','Araña Madre','Comandante Fell'] },
  { id:'thread-senor-fell', name:'El Señor Fell — antagonista principal', status:'emerging',
    description:'Sombra que se alza. Tiene sirvientes organizados (guerreros, pícaros, arqueros) + comandantes. La Capital ya tiene conocimiento de su existencia. Su origen está conectado con el Norte Congelado. Insignia copiada por Zyren en scroll que lleva Esdas.',
    characters:[] },

  // ── FACCIONES ──
  { id:'thread-velo-elmyra', name:'Velo Elmyra y Aether Grove', status:'active',
    description:'Santuario oculto guardado por Zyren y Nira. Lugar donde el grupo aprenderá sobre el equilibrio de Ardaetheros. Miembros conocidos: Zyren (líder), Nira (guardiana), Zael (druida), Idris (druida), Isis (anciana).',
    characters:['Zyren','Nira','Zael','Idris','Isis'] },
  { id:'thread-sunbound', name:'Sunbound Druids — facción a conocer', status:'emerging',
    description:'Druidas de la luz solar — opuestos filosóficos al Velo Elmyra (terrestre vs aéreo). Base en Solmira. Líder: Sura. Pegamento social: Barek. Sakura los menciona por primera vez al grupo en Aether Grove.',
    characters:['Sura','Barek','Sakura'] },
  { id:'thread-paladines-capital', name:'Paladines de la Capital — facción a desarrollar', status:'dormant',
    description:'Facción institucional de la Capital. Conocen la amenaza del Fell Lord. Miembros: Barak (hermano de Barek), Sova (priest). Conexión con el pasado de Tyrell — fueron los que lo encontraron en las calles.',
    characters:['Barak','Sova'] },
  { id:'thread-familia-al-nasir', name:'Familia Al-Nasir — nobleza independiente', status:'dormant',
    description:'Familia noble de la Capital. Construyó su poder apoyando a reyes — acceso a casi todo, lealtad a casi nadie en particular. Representante: Ramis Al-Nasir. Su ayuda no se paga con dinero.',
    characters:['Ramis Al-Nasir'] },

  // ── HILOS DE PERSONAJES ──
  { id:'thread-deuda-esdas-relyo', name:'La deuda de Esdas con Relyo', status:'active',
    description:'Relyo le salvó la vida a Esdas en el primer combate (lobo). Esdas siente impotencia y deuda emocional. Esta deuda puede manifestarse en momentos clave a futuro.',
    characters:['Esdas','Relyo'] },
  { id:'thread-rechazo-esdas-tyrell', name:'El rechazo inexplicable de Esdas hacia Tyrell', status:'active',
    description:'Esdas siente enojo al ver la piel dracónica de Tyrell — sin razón aparente. CONEXIÓN OCULTA: linaje dracónico de Esdas (el jugador sabe, el personaje no). Debe mantenerse como misterio, no como sabotaje.',
    characters:['Esdas','Tyrell'] },
  { id:'thread-linaje-dracónico-esdas', name:'Linaje dracónico oculto de Esdas', status:'dormant',
    description:'El jugador lo sabe, el personaje no. Hilo a revelar gradualmente. Conexión con su rechazo hacia Tyrell. Posible conexión con su despertar arcano (Firebolt nat 20).',
    characters:['Esdas'] },
  { id:'thread-pasado-tyrell', name:'El pasado de Tyrell — calles, juramentos, paladines', status:'active',
    description:'Tyrell creció en las calles antes de que los paladines lo encontraran. Conexión futura con Pip — espejo de su pasado. Conexión futura con Barak y Sova en la Capital. El juramento a Reynera es eco de su naturaleza protectora.',
    characters:['Tyrell','Pip','Barak','Sova','Reynera'] },
  { id:'thread-marido-reynera', name:'El marido de Reynera — futuro general corrupto', status:'dormant',
    description:'Reynera es viuda — su marido era aventurero. Aparecerá como figura corrupta del Fell Lord. Punto de quiebre emocional para Tyrell por su juramento a ella. Hilo LATENTE — el DM lo activa cuando tenga peso narrativo.',
    characters:['Reynera','Tyrell'] },
  { id:'thread-origen-owling', name:'El origen de los Owling', status:'emerging',
    description:'Isis mencionará a Boyd que los Owling vienen de la otra parte del mundo. Solo a Boyd, solo una vez. Hilo de identidad para Boyd — conexión con sus raíces que el personaje no conocía.',
    characters:['Boyd','Isis'] },
  { id:'thread-ati-rac', name:'Ati — la voz tatuada de Rac', status:'active',
    description:'Smiley face tatuada en la mano de Rac. Le habla — le dijo que no confíe en el mago (Esdas) ni en el paladín (Tyrell). Sakura nota el tatuaje con fascinación. Naturaleza de Ati: a desarrollar.',
    characters:['Rac','Sakura'] },

  // ── HILOS DE ITEMS Y CRAFTING ──
  { id:'thread-insignia-fell-lord', name:'La insignia del Fell Lord — scroll de Esdas', status:'active',
    description:'Símbolo del Fell Lord copiado por Zyren en un scroll y entregado a Esdas. Círculo de hierro verde oscuro con líneas interlazadas y mini círculos. Símbolo de destrucción y control. Pista clave para identificar agentes Fell.',
    characters:['Esdas','Zyren'] },
  { id:'thread-espada-gigante', name:'La espada gigante del Comandante Fell — para Rac', status:'active',
    description:'Espada de ~2 metros del Comandante Fell del Encuentro 3. Rac la quiere desde que la ve. Con su STR actual puede levantarla pero Speed reducida a 20ft. Smith podría repararla y adaptarla — requiere recursos y tiempo.',
    characters:['Rac','Smith'] },
  { id:'thread-daga-colmillo-corrompido', name:'La Daga del Colmillo Corrompido — crafting de Esdas', status:'emerging',
    description:'Daga del Pícaro Fell (Encuentro 3) + Colmillo del Lobo Corrupto (Encuentro 1) + proceso alquímico. Sakura puede preparar el colmillo. Smith hace la parte física pero necesita ayuda arcana. Requiere ingrediente raro adicional (a definir).\n\nAdvertencia: si el Fell dentro de la daga crece sin control, podría volverse peligrosa para Esdas. Hilo latente a activar.',
    characters:['Esdas','Sakura','Smith'] },
  { id:'thread-bandidos-aldea', name:'Los bandidos y su aldea atacada', status:'emerging',
    description:'5 bandidos del camino a Solmira. De una aldea al norte del Valle Aethon. Algo atacó su aldea hace 3 meses — perdieron todo. POSIBLE hilo Fell sin confirmar. La decisión moral del grupo afecta la relación con Pip y Mila.',
    characters:[] },

  // ── HILOS DE OTROS NPCs ──
  { id:'thread-druida-antigua', name:'La "druida más sabia y antigua que Zyren"', status:'emerging',
    description:'Zyren la mencionó antes de separarse del grupo. No dio nombre. Primera vez que el grupo escucha que existe alguien con MÁS conocimiento que Zyren. Probablemente tiene respuestas sobre el origen del Fell Lord y sobre la naturaleza de la resonancia del grupo.\n\n⚠ Nombre y ubicación pendientes — a desarrollar con el DM.',
    characters:['Zyren'] },
  { id:'thread-zael-relyo', name:'La conexión inexplicable entre Zael y Relyo', status:'dormant',
    description:'Relyo siente algo familiar con Zael — y al revés. Ninguno de los dos sabría explicar por qué. Relyo es el primero del grupo en tomarlo en serio como combatiente.',
    characters:['Relyo','Zael'] },
  { id:'thread-barak-barek', name:'Barak y Barek — hermanos con caminos opuestos', status:'dormant',
    description:'Hermanos: Barek (druida Sunbound) y Barak (paladín de la Capital). Mismo origen, caminos completamente distintos. La dinámica cuando el grupo los ponga en la misma sala tiene MUCHO potencial narrativo.',
    characters:['Barak','Barek'] },
  { id:'thread-pueblo-derrota', name:'El pueblo que será arrasado', status:'dormant',
    description:'Momento de alto impacto emocional confirmado. El DM debe construir vínculos del grupo con ese pueblo ANTES del ataque. La derrota redefine la urgencia de la campaña. Nombre del pueblo pendiente.',
    characters:[] }
];
