/* ── CLASS PRESETS: personajes jugadores ── */

module.exports = {
  rac: {
    className:'Bárbaro',
    equipment:[
      {itemId:'greataxe', equipped:true},
      {itemId:'handaxe',  equipped:true},
      {itemId:'unarmed',  equipped:true}
    ],
    saveProfs:['str','con'],
    skillProfs:[
      {name:'Athletics',nameEs:'Atletismo',ability:'str'},
      {name:'Intimidation',nameEs:'Intimidación',ability:'cha'},
      {name:'Survival',nameEs:'Supervivencia',ability:'wis'},
      {name:'Perception',nameEs:'Percepción',ability:'wis'}
    ],
    resources:[
      { key:'rage', name:'Rage', nameEs:'Furia', kind:'uses', restoresOn:'long',
        desc:'Bonus action para entrar en Furia. Usos máximos escalan con nivel.' }
    ],
    levelFeatures:[
      { level:1, name:'Rage', nameEs:'Furia',
        desc:'Bonus action para entrar en Furia (gasta 1 uso). Mientras dura (1 min): +daño en ataques STR cuerpo a cuerpo · resistencia bludgeoning/piercing/slashing · ventaja en STR checks/saves · no podés lanzar ni concentrarte en hechizos.\nUsos por long rest: Nv 1→2, 3→3, 6→4, 12→5, 17→6, 20→ilimitada.\nDaño bonus: Nv 1-8 → +2, 9-15 → +3, 16+ → +4.' },
      { level:1, name:'Unarmored Defense', nameEs:'Defensa sin Armadura',
        desc:'Sin armadura: CA = 10 + DEX mod + CON mod (= 14). Podés usar escudo sin perderlo.' },
      { level:2, name:'Reckless Attack', nameEs:'Ataque Imprudente',
        desc:'Tu primer ataque STR cuerpo a cuerpo del turno: ventaja en TODOS los ataques de ese turno. Penal: ataques contra vos también con ventaja hasta tu próximo turno.' },
      { level:2, name:'Danger Sense', nameEs:'Sentido del Peligro',
        desc:'Ventaja en DEX saves contra efectos que podés ver (trampas, AoE de hechizos). No funciona si estás ciego, sordo o incapacitado.' },
      // TODO subclass: cuando Rac elija su Primal Path, agregar entries
      // de level:3, level:6, level:10, level:14 con los features de esa
      // subclase específica (ej: Berserker → Frenzy a Nv 3, Mindless Rage
      // a Nv 6, Intimidating Presence a Nv 10, Retaliation a Nv 14).
      { level:3, name:'Primal Path', nameEs:'Senda Primal',
        desc:'Elegí tu subclase: Berserker (frenesí), Totem Warrior (espíritus animales), Wild Magic (caos mágico), Zealot (divino), Ancestral Guardian, Storm Herald, etc. Cada path tiene features propios en Nv 3, 6, 10, 14.' },
      { level:4, name:'Ability Score Improvement', nameEs:'Mejora de Stats (ASI)',
        desc:'+2 a una stat, o +1 a dos stats (máx 20), o un Feat.' },
      { level:5, name:'Extra Attack', nameEs:'Ataque Extra',
        desc:'Cuando hagas la Action Attack, podés atacar 2 veces en lugar de 1.' },
      { level:5, name:'Fast Movement', nameEs:'Movimiento Veloz',
        desc:'+10 ft de velocidad sin armadura pesada. Velocidad total: 40 ft.' },
      { level:6, name:'Path Feature', nameEs:'Feature de Senda',
        desc:'Habilidad de tu subclase (ej: Mindless Rage del Berserker, Aspect of the Beast del Totem).' },
      { level:7, name:'Feral Instinct', nameEs:'Instinto Salvaje',
        desc:'Ventaja en initiative. Si te sorprenden, podés entrar en Furia y actuar normalmente (no contás surprised mientras rage).' },
      { level:8, name:'Ability Score Improvement', nameEs:'ASI', desc:'+2 a una stat, o +1 a dos, o un Feat.' },
      { level:9, name:'Brutal Critical (1 dado)', nameEs:'Crítico Brutal',
        desc:'En un crítico cuerpo a cuerpo, tirás 1 dado de daño extra (sube a 2 en Nv 13, 3 en Nv 17).' },
      { level:10, name:'Path Feature', nameEs:'Feature de Senda',
        desc:'Segundo feature de subclase (ej: Intimidating Presence del Berserker).' },
      { level:11, name:'Relentless Rage', nameEs:'Furia Implacable',
        desc:'Si recibís daño que te baja a 0 HP estando en Furia: CON save DC 10 (DC sube +5 por cada éxito previo en el día). Si pasás, quedás en 1 HP.' },
      { level:12, name:'Ability Score Improvement', nameEs:'ASI', desc:'+2/+1+1/feat.' },
      { level:13, name:'Brutal Critical (2 dados)', nameEs:'Crítico Brutal +', desc:'Crítico tira 2 dados extra de daño.' },
      { level:14, name:'Path Feature', nameEs:'Feature de Senda',
        desc:'Tercer feature de subclase (ej: Retaliation del Berserker).' },
      { level:15, name:'Persistent Rage', nameEs:'Furia Persistente',
        desc:'Tu Furia ya no termina automáticamente por no atacar/recibir daño. Solo termina cuando vos querés, te dejan inconsciente, o pasaron 1 min.' },
      { level:16, name:'Ability Score Improvement', nameEs:'ASI', desc:'+2/+1+1/feat.' },
      { level:17, name:'Brutal Critical (3 dados)', nameEs:'Crítico Brutal maestro', desc:'Crítico tira 3 dados extra.' },
      { level:18, name:'Indomitable Might', nameEs:'Poderío Indómito',
        desc:'Si tu STR check sale menor a tu STR score, usás tu STR como resultado.' },
      { level:19, name:'Ability Score Improvement', nameEs:'ASI', desc:'+2/+1+1/feat.' },
      { level:20, name:'Primal Champion', nameEs:'Campeón Primal',
        desc:'+4 a STR y +4 a CON. Máximo de esas stats sube a 24.' }
    ],
    spells:null
  },
  relyo: {
    className:'Monje',
    equipment:[
      {itemId:'quarterstaff',   equipped:true},
      {itemId:'unarmed-monk',   equipped:true},
      {itemId:'dagger',         equipped:false}
    ],
    saveProfs:['str','dex'],
    skillProfs:[
      {name:'Acrobatics',nameEs:'Acrobacia',ability:'dex'},
      {name:'Stealth',nameEs:'Sigilo',ability:'dex'},
      {name:'Insight',nameEs:'Perspicacia',ability:'wis'},
      {name:'Athletics',nameEs:'Atletismo',ability:'str'}
    ],
    resources:[
      { key:'ki', name:'Ki points', nameEs:'Puntos de Ki', kind:'uses', restoresOn:'short',
        desc:'Igual al nivel del Monje. Recargan en short rest. Se gastan para Flurry/Patient Defense/Step of the Wind y otras técnicas a niveles altos.' }
    ],
    levelFeatures:[
      { level:1, name:'Martial Arts', nameEs:'Artes Marciales',
        desc:'Usás DEX (no STR) en monk weapons y unarmed strikes. Daño base: 1d4 (Nv 1-4) → 1d6 (Nv 5) → 1d8 (Nv 11) → 1d10 (Nv 17). Cuando atacás con Action usando monk weapon/unarmed, podés hacer un unarmed strike como Bonus Action.' },
      { level:1, name:'Unarmored Defense', nameEs:'Defensa sin Armadura',
        desc:'Sin armadura ni escudo: CA = 10 + DEX mod + WIS mod (= 15).' },
      { level:2, name:'Ki', nameEs:'Ki',
        desc:'Ki save DC = 8 + prof + WIS mod = 12. Los puntos = nivel monje, recargan en short rest. Se gastan para activar técnicas.' },
      { level:2, name:'Flurry of Blows', nameEs:'Lluvia de Golpes',
        desc:'1 Ki. Después de hacer Attack en tu turno: 2 unarmed strikes adicionales como Bonus Action.' },
      { level:2, name:'Patient Defense', nameEs:'Defensa Paciente',
        desc:'1 Ki. Bonus Action: tomás Dodge (ataques contra vos con desventaja, DEX saves con ventaja hasta tu próximo turno).' },
      { level:2, name:'Step of the Wind', nameEs:'Paso del Viento',
        desc:'1 Ki. Bonus Action: Disengage o Dash, y tu salto se dobla por este turno.' },
      { level:2, name:'Unarmored Movement', nameEs:'Movimiento sin Armadura',
        desc:'+10 ft de velocidad sin armadura/escudo. Escala: Nv 2→+10, 6→+15, 10→+20, 14→+25, 18→+30.' },
      // TODO subclass: cuando Relyo elija Monastic Tradition, agregar
      // entries de level:3, 6, 11, 17 con features de esa subclase
      // (ej: Open Hand → Open Hand Technique a Nv 3, Wholeness of Body
      // a Nv 6, Tranquility a Nv 11, Quivering Palm a Nv 17).
      // TODO subclass-resource: Way of Shadow añade Shadow Arts (recursos
      // de Ki para hechizos), Four Elements añade Disciplines, etc.
      { level:3, name:'Monastic Tradition', nameEs:'Tradición Monástica',
        desc:'Elegí tu subclase: Way of the Open Hand (artes marciales puras), Shadow (asesino sigiloso), Four Elements (manipulación elemental), Long Death, Sun Soul, Kensei, Drunken Master, etc.' },
      { level:3, name:'Deflect Missiles', nameEs:'Desviar Proyectiles',
        desc:'Reaction al ser blanco de ataque ranged: reducís el daño en 1d10 + DEX mod + nivel monje. Si lo reducís a 0, atrapás el proyectil y podés tirarlo de vuelta gastando 1 Ki (atque +DEX, daño d4 + bono).' },
      { level:4, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:4, name:'Slow Fall', nameEs:'Caída Lenta',
        desc:'Reaction al caer: reducís el daño de la caída en 5 × nivel monje (= 20 a Nv 4).' },
      { level:5, name:'Extra Attack', nameEs:'Ataque Extra', desc:'Atacás 2 veces con la Action Attack.' },
      { level:5, name:'Stunning Strike', nameEs:'Golpe Aturdidor',
        desc:'1 Ki al pegar con ataque de melee weapon: el objetivo tira CON save DC 12 o queda Stunned hasta el final de tu próximo turno.' },
      { level:6, name:'Ki-Empowered Strikes', nameEs:'Golpes Imbuidos de Ki',
        desc:'Tus unarmed strikes cuentan como mágicos para superar resistencias/inmunidades.' },
      { level:6, name:'Tradition Feature', nameEs:'Feature de Tradición',
        desc:'Habilidad de tu subclase.' },
      { level:7, name:'Evasion', nameEs:'Evasión',
        desc:'Cuando hagas DEX save contra un efecto que normalmente hace mitad de daño: si pasás, no recibís NADA; si fallás, recibís solo mitad.' },
      { level:7, name:'Stillness of Mind', nameEs:'Mente Serena',
        desc:'Action. Terminás un efecto de charm o fear sobre vos.' },
      { level:8, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:9, name:'Unarmored Movement (vertical)', nameEs:'Movimiento sin Armadura mejorado',
        desc:'Podés correr por paredes verticales y sobre agua durante tu turno sin caer.' },
      { level:10, name:'Purity of Body', nameEs:'Pureza Corporal', desc:'Inmune a enfermedades y venenos.' },
      { level:11, name:'Tradition Feature', nameEs:'Feature de Tradición', desc:'Segundo feature de subclase.' },
      { level:12, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:13, name:'Tongue of the Sun and Moon', nameEs:'Lengua del Sol y la Luna',
        desc:'Entendés todas las lenguas habladas. Cualquier criatura que pueda entender una lengua puede entenderte.' },
      { level:14, name:'Diamond Soul', nameEs:'Alma de Diamante',
        desc:'Proficiency en TODOS los saves. Si fallás un save, podés gastar 1 Ki para repetirlo (debés aceptar el segundo).' },
      { level:15, name:'Timeless Body', nameEs:'Cuerpo Atemporal',
        desc:'Tu cuerpo no envejece ni necesita comida/agua.' },
      { level:16, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:17, name:'Tradition Feature', nameEs:'Feature de Tradición', desc:'Tercer feature de subclase (capstone).' },
      { level:18, name:'Empty Body', nameEs:'Cuerpo Vacío',
        desc:'4 Ki. Action: invisible 1 min + resistencia a todo el daño (excepto force). 8 Ki: castear Astral Projection sin componentes.' },
      { level:19, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:20, name:'Perfect Self', nameEs:'Yo Perfecto',
        desc:'Al inicio de cada combate si tenés 0 Ki, recuperás 4 puntos.' }
    ],
    spells:null
  },
  tyrell: {
    className:'Paladín',
    equipment:[
      {itemId:'shortsword', equipped:true},
      {itemId:'spear',      equipped:false},
      {itemId:'unarmed',    equipped:true}
    ],
    saveProfs:['wis','cha'],
    skillProfs:[
      {name:'Athletics',nameEs:'Atletismo',ability:'str'},
      {name:'Persuasion',nameEs:'Persuasión',ability:'cha'},
      {name:'Religion',nameEs:'Religión',ability:'int'},
      {name:'Insight',nameEs:'Perspicacia',ability:'wis'}
    ],
    resources:[
      { key:'divine-sense', name:'Divine Sense', nameEs:'Sentido Divino', kind:'uses', restoresOn:'long',
        desc:'1 + CHA mod por long rest (= 1 actualmente).' },
      { key:'lay-on-hands', name:'Lay on Hands', nameEs:'Imposición de Manos', kind:'pool', restoresOn:'long',
        desc:'Pool de 5 × nivel paladín HP. Gastá HP del pool para curar o purgar (5 HP por enfermedad/veneno).' },
      { key:'channel-divinity', name:'Channel Divinity', nameEs:'Canalizar Divinidad', kind:'uses', restoresOn:'short',
        desc:'1 uso por short rest (desde Nv 3). Las opciones específicas dependen del Sacred Oath elegido — agregar features a levelFeatures cuando Tyrell se comprometa con un juramento.' }
    ],
    levelFeatures:[
      { level:1, name:'Divine Sense', nameEs:'Sentido Divino',
        desc:'Action. Hasta tu próximo turno, conocer ubicación de celestiales/infernales/no-muertos no escondidos a 60 ft. Sentir lugares/objetos consagrados/profanados. Usos: 1 + CHA mod / long rest.' },
      { level:1, name:'Lay on Hands', nameEs:'Imposición de Manos',
        desc:'Pool de 5 × nivel HP. Action: tocás criatura, gastás HP del pool para curar. 5 HP del pool puede purgar 1 enfermedad o veneno.' },
      { level:2, name:'Fighting Style: Defense', nameEs:'Estilo de Combate: Defensa',
        desc:'+1 CA mientras uses armadura. (Otras opciones: Dueling, Great Weapon, Protection.)' },
      { level:2, name:'Spellcasting (CHA)', nameEs:'Lanzamiento de Hechizos (CHA)',
        desc:'Half-caster. Spell save DC 10 · Spell attack +2. Preparás CHA mod + ½ nivel paladín hechizos. Conocés todos los hechizos de Paladín de tu nivel.' },
      { level:2, name:'Divine Smite', nameEs:'Castigo Divino',
        desc:'Al pegar con arma de melee, gastá un spell slot: +2d8 radiante (nivel 1) hasta +5d8 (nivel 4-5). +1d8 contra no-muerto/infernal.' },
      { level:3, name:'Divine Health', nameEs:'Salud Divina', desc:'Inmune a enfermedades mundanas.' },
      // TODO subclass: cuando Tyrell elija su Sacred Oath, agregar entries
      // de level:3, 7, 15, 20 con features del oath específico (ej:
      // Devotion → Sacred Weapon + Turn the Unholy a Nv 3, Aura of Devotion
      // a Nv 7, Purity of Spirit a Nv 15, Holy Nimbus a Nv 20).
      { level:3, name:'Sacred Oath', nameEs:'Juramento Sagrado',
        desc:'Elegí tu subclase: Oath of Devotion (clásico), Vengeance (cazador), Ancients (verde), Conquest (oscuro), Crown (rey), Glory (héroe), Redemption (pacifista), Watchers (vigilante). Cada oath da Channel Divinity options + tenets.' },
      { level:3, name:'Channel Divinity', nameEs:'Canalizar Divinidad',
        desc:'1/short rest (ya cableado como recurso, se desbloquea automáticamente al subir a Nv 3). Las dos opciones de canal específicas dependen del Sacred Oath elegido — agregar features de oath cuando Tyrell se comprometa.' },
      { level:4, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:5, name:'Extra Attack', nameEs:'Ataque Extra', desc:'2 ataques con Action Attack. Slots de nivel 2 desbloqueados.' },
      { level:6, name:'Aura of Protection', nameEs:'Aura de Protección',
        desc:'Vos y aliados a 10 ft suman tu CHA mod a TODOS los saves (mínimo +1). A Nv 18, el aura crece a 30 ft.' },
      { level:7, name:'Sacred Oath Feature', nameEs:'Feature de Juramento',
        desc:'Aura específica del oath (ej: Aura of Devotion: inmunidad a charm para vos y aliados a 10 ft).' },
      { level:8, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:9, name:'Slots de nivel 3', nameEs:'Slots de nivel 3', desc:'Desbloqueás slots de hechizo de nivel 3.' },
      { level:10, name:'Aura of Courage', nameEs:'Aura de Coraje',
        desc:'Vos y aliados a 10 ft no pueden ser frightened mientras estés consciente. A Nv 18, el aura crece a 30 ft.' },
      { level:11, name:'Improved Divine Smite', nameEs:'Castigo Divino Mejorado',
        desc:'Cada ataque cuerpo a cuerpo con arma hace +1d8 radiante (sin gastar slot). Stack con Divine Smite normal.' },
      { level:12, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:13, name:'Slots de nivel 4', nameEs:'Slots de nivel 4', desc:'Desbloqueás slots de hechizo de nivel 4.' },
      { level:14, name:'Cleansing Touch', nameEs:'Toque Purificador',
        desc:'CHA mod usos / long rest. Action: terminás 1 hechizo sobre vos o una criatura voluntaria.' },
      { level:15, name:'Sacred Oath Feature', nameEs:'Feature de Juramento',
        desc:'Tercer feature del oath.' },
      { level:16, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:17, name:'Slots de nivel 5', nameEs:'Slots de nivel 5', desc:'Desbloqueás slots de hechizo de nivel 5 (máximo).' },
      { level:18, name:'Aura mejorada', nameEs:'Auras a 30 ft',
        desc:'Tus auras (Protection, Courage, y la del oath) suben de 10 ft a 30 ft de radio.' },
      { level:19, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:20, name:'Sacred Oath Capstone', nameEs:'Capstone del Juramento',
        desc:'Habilidad definitiva del oath (ej: Avenging Angel del Vengeance, Holy Nimbus del Devotion).' }
    ],
    spellSaveDC:10,
    spellAtk:'+2',
    spellSlots:{ '1': 2 },
    cantripsData:[],
    spellList:[
      // Nivel 1 (disponible desde Nv 2)
      { name:'Bless', nameEs:'Bendición', level:1, prepared:true, school:'enchantment', shape:'3 criaturas a 30 ft',
        desc:'Concentración, 1 min. Hasta 3 criaturas: +1d4 a tiradas de ataque y saves mientras dure.' },
      { name:'Cure Wounds', nameEs:'Curar Heridas', level:1, prepared:false, school:'evocation', shape:'Toque',
        desc:'Toque. Curar 1d8 + CHA mod HP. +1d8 por slot extra.' },
      { name:'Shield of Faith', nameEs:'Escudo de Fe', level:1, prepared:false, school:'abjuration', shape:'1 criatura @ 60 ft',
        desc:'Concentración, 10 min. +2 CA a una criatura dentro de 60 ft.' },
      { name:'Command', nameEs:'Orden', level:1, prepared:false, school:'enchantment', shape:'1 criatura @ 60 ft',
        desc:'WIS save o cumplir orden de 1 palabra (drop/flee/halt/approach/grovel) en su próximo turno.' },
      { name:'Compelled Duel', nameEs:'Duelo Forzado', level:1, prepared:false, school:'enchantment', shape:'1 criatura @ 30 ft',
        desc:'Concentración, 1 min. WIS save o desventaja contra otros + no puede alejarse más de 30 ft de Tyrell voluntariamente.' },
      { name:'Divine Favor', nameEs:'Favor Divino', level:1, prepared:false, school:'evocation', shape:'Self · Concentración',
        desc:'Bonus Action. Concentración, 1 min. Tus ataques con arma hacen +1d4 radiante extra.' },
      { name:'Heroism', nameEs:'Heroísmo', level:1, prepared:false, school:'enchantment', shape:'1 criatura · Toque',
        desc:'Concentración, 1 min. Una criatura es inmune a frightened y gana CHA mod temp HP al inicio de cada turno.' },
      { name:'Protection from Evil and Good', nameEs:'Protección contra el Mal y el Bien', level:1, prepared:false, school:'abjuration', shape:'1 criatura · Toque',
        desc:'Concentración, 10 min. Contra aberrations, celestials, elementals, fey, fiends, undead: ataques con desventaja y no pueden charm/frighten/poseer al objetivo.' },
      { name:'Searing Smite', nameEs:'Castigo Ardiente', level:1, prepared:false, school:'evocation', shape:'Self · Concentración',
        desc:'Bonus Action. Concentración, 1 min. Próximo hit melee: +1d6 fuego y CON save c/turno o sigue ardiendo 1d6.' },
      { name:'Thunderous Smite', nameEs:'Castigo Atronador', level:1, prepared:false, school:'evocation', shape:'Self',
        damage:'2d6', damageType:'thunder', saveType:'str', halfOnSave:false,
        desc:'Bonus Action. Próximo hit melee este turno: +2d6 thunder + STR save o empujado 10 ft y prone.' },
      { name:'Wrathful Smite', nameEs:'Castigo Iracundo', level:1, prepared:false, school:'evocation', shape:'Self · Concentración',
        damage:'1d6', damageType:'psychic',
        desc:'Bonus Action. Concentración, 1 min. Próximo hit melee: +1d6 psychic + WIS save o frightened.' },
      { name:'Sanctuary', nameEs:'Santuario', level:1, prepared:false, school:'abjuration', shape:'1 criatura @ 30 ft',
        desc:'Bonus Action. 1 min. Quien quiera atacarla tira WIS save o pierde el ataque/hechizo (con AoE no aplica).' },

      // Nivel 2 (disponible desde Nv 5)
      { name:'Aid', nameEs:'Auxilio', level:2, prepared:false, school:'abjuration', shape:'3 criaturas @ 30 ft',
        desc:'Action. 8 h. +5 a HP max y actual de hasta 3 criaturas. +5 más por slot extra.' },
      { name:'Branding Smite', nameEs:'Castigo Marcador', level:2, prepared:false, school:'evocation', shape:'Self · Concentración',
        damage:'2d6', damageType:'radiant',
        desc:'Bonus Action. Concentración, 1 min. Próximo hit con arma: +2d6 radiante + objetivo brilla (no puede estar invisible).' },
      { name:'Find Steed', nameEs:'Encontrar Montura', level:2, prepared:false, school:'conjuration', shape:'10 min de ritual',
        desc:'Invocás una montura celestial/feérica/infernal (warhorse/pony/etc.) leal hasta morir. Telepatía 1 milla.' },
      { name:'Lesser Restoration', nameEs:'Restauración Menor', level:2, prepared:false, school:'abjuration', shape:'1 criatura · Toque',
        desc:'Action. Curás 1 condición de la criatura: blinded, deafened, paralyzed, poisoned, o una enfermedad.' },
      { name:'Magic Weapon', nameEs:'Arma Mágica', level:2, prepared:false, school:'transmutation', shape:'Self · Concentración',
        desc:'Bonus Action. Concentración, 1 h. Tu arma no-mágica cuenta como mágica y +1 al ataque y daño. +2 si slot Nv 4, +3 si Nv 6.' },
      { name:'Zone of Truth', nameEs:'Zona de Verdad', level:2, prepared:false, school:'enchantment', shape:'⬛ 15-ft esfera @ 60 ft',
        desc:'10 min. Criaturas dentro tiran CHA save o no pueden mentir conscientemente. Cada criatura sabe si está afectada.' },

      // Nivel 3 (disponible desde Nv 9)
      { name:'Aura of Vitality', nameEs:'Aura de Vitalidad', level:3, prepared:false, school:'evocation', shape:'⬛ 30-ft self aura · Concentración',
        desc:'Concentración, 1 min. Bonus Action cada turno: curar 2d6 HP a una criatura en el aura (incluido vos).' },
      { name:'Blinding Smite', nameEs:'Castigo Cegador', level:3, prepared:false, school:'evocation', shape:'Self · Concentración',
        damage:'3d8', damageType:'radiant',
        desc:'Bonus Action. Concentración, 1 min. Próximo hit: +3d8 radiante + CON save o blinded.' },
      { name:'Crusader\'s Mantle', nameEs:'Manto del Cruzado', level:3, prepared:false, school:'evocation', shape:'⬛ 30-ft self aura · Concentración',
        desc:'Concentración, 1 min. Aliados a 30 ft hacen +1d4 radiante en sus ataques con arma.' },
      { name:'Daylight', nameEs:'Luz del Día', level:3, prepared:false, school:'evocation', shape:'⬛ 60-ft esfera @ 60 ft',
        desc:'1 h. Brillo + dim light a 60 ft cada uno. Disipa magical darkness ≤ Nv 3.' },
      { name:'Dispel Magic', nameEs:'Disipar Magia', level:3, prepared:false, school:'abjuration', shape:'1 criatura/objeto @ 120 ft',
        desc:'Action. Termina hechizos de Nv ≤ 3 sobre el blanco automáticamente. Para hechizos mayores: ability check vs DC 10+nivel.' },
      { name:'Revivify', nameEs:'Revivir', level:3, prepared:false, school:'necromancy', shape:'Toque, criatura muerta <1 min',
        desc:'Action. Revive una criatura muerta hace menos de 1 min con 1 HP. No restaura miembros perdidos.' },

      // Nivel 4 (disponible desde Nv 13)
      { name:'Aura of Life', nameEs:'Aura de Vida', level:4, prepared:false, school:'abjuration', shape:'⬛ 30-ft self aura',
        desc:'Concentración, 10 min. Tu aura: resistencia a necrotic. Si un aliado en 0 HP empieza turno en el aura, vuelve a 1 HP.' },
      { name:'Death Ward', nameEs:'Custodia Mortal', level:4, prepared:false, school:'abjuration', shape:'1 criatura · Toque',
        desc:'8 h. Primera vez que el objetivo bajaría a 0 HP, queda en 1 en su lugar. Termina al gatillarse.' },
      { name:'Staggering Smite', nameEs:'Castigo Tambaleante', level:4, prepared:false, school:'evocation', shape:'Self',
        damage:'4d6', damageType:'psychic', saveType:'wis', halfOnSave:false,
        desc:'Bonus Action. Próximo hit: +4d6 psychic + WIS save o desventaja en ataques + no puede reactions hasta fin de SU próximo turno.' },

      // Nivel 5 (disponible desde Nv 17)
      { name:'Banishing Smite', nameEs:'Castigo Destierro', level:5, prepared:false, school:'abjuration', shape:'Self · Concentración',
        damage:'5d10', damageType:'force',
        desc:'Bonus Action. Concentración, 1 min. Próximo hit: +5d10 force + si baja al objetivo a ≤ 50 HP, lo desterrás a otro plano.' },
      { name:'Circle of Power', nameEs:'Círculo de Poder', level:5, prepared:false, school:'abjuration', shape:'⬛ 30-ft self aura · Concentración',
        desc:'Concentración, 10 min. Aliados en el aura tienen ventaja en saves contra hechizos, y los efectos que les harían mitad de daño no les hacen nada si pasan.' },
      { name:'Destructive Wave', nameEs:'Onda Destructiva', level:5, prepared:false, school:'evocation', shape:'⬛ 30-ft self esfera',
        desc:'Action. CON save o 5d6 thunder + 5d6 radiante (o necrotic, elegís) + prone. Mitad si pasa, sin prone.' }
    ]
  },
  boyd: {
    className:'Druida',
    speed:{ walk:30, fly:30 },
    equipment:[
      {itemId:'dagger',   equipped:true},
      {itemId:'scimitar', equipped:false},
      {itemId:'unarmed',  equipped:true}
    ],
    saveProfs:['int','wis'],
    skillProfs:[
      {name:'Nature',nameEs:'Naturaleza',ability:'int'},
      {name:'Animal Handling',nameEs:'Trato con Animales',ability:'wis'},
      {name:'Perception',nameEs:'Percepción',ability:'wis'},
      {name:'Survival',nameEs:'Supervivencia',ability:'wis'}
    ],
    campaignNotes:[
      { type:'info', title:'Vuelo racial (Owlin) — 30 ft',
        desc:'Boyd es Owlin y tiene velocidad de vuelo racial de 30 ft (planear). Reglas:\n• El vuelo es independiente del Wild Shape — siempre disponible mientras Boyd esté en su forma normal.\n• Necesita las manos libres y no llevar armadura pesada.\n• Wild Shape no le da vuelo hasta Nv 8 (CR 1 con velocidad de vuelo) — son sistemas separados.\n• En interiores bajos no puede usar vuelo prolongado.' }
    ],
    resources:[
      { key:'wild-shape', name:'Wild Shape', nameEs:'Forma Salvaje', kind:'uses', restoresOn:'short',
        desc:'2 transformaciones por short rest (ilimitadas a Nv 20).' },
      { key:'natural-recovery', name:'Natural Recovery', nameEs:'Recuperación Natural', kind:'uses', restoresOn:'long',
        desc:'1 uso por long rest, durante un short rest: recuperar slots cuya suma de niveles ≤ ½ nivel druida.' }
    ],
    levelFeatures:[
      { level:1, name:'Druidic', nameEs:'Druídico',
        desc:'Idioma secreto de los druidas. Podés dejar mensajes en objetos/lugares solo legibles por otros druidas (WIS check para detectarlos).' },
      { level:1, name:'Spellcasting (WIS)', nameEs:'Lanzamiento de Hechizos (WIS)',
        desc:'Full caster. Spell save DC = 8+prof+WIS · Spell attack = prof+WIS. Preparás WIS mod + nivel druida hechizos por long rest. Foco druídico reemplaza componentes materiales.' },
      { level:2, name:'Wild Shape', nameEs:'Forma Salvaje',
        desc:'Action. Transformate en una bestia que hayas visto. Restricciones por nivel:\n• Nv 2: CR ¼ máx, sin vuelo ni nado\n• Nv 4: CR ½ máx, podés nadar\n• Nv 8: CR 1 máx, podés volar\nHP de la bestia (separados); al llegar a 0 volvés. Duración: ½ nivel druida en horas. No podés lanzar hechizos en forma de bestia (excepto a Nv 18+).' },
      // TODO subclass: Boyd ya eligió Circle of the Land (Bosque) a Nv 2.
      // Los features iniciales están cargados (Bonus Cantrip, Natural
      // Recovery, Land Spells). Para subclases distintas (Moon, Dreams,
      // Shepherd, Spores, Stars, Wildfire) habría que reemplazar estos
      // entries con los del circle elegido. Moon en particular es muy
      // distinto: cambia el comportamiento de Wild Shape drásticamente.
      { level:2, name:'Druid Circle', nameEs:'Círculo Druídico',
        desc:'Elegí tu subclase: Land (varía: Bosque, Montaña, Desierto...), Moon (Wild Shape mejorado), Dreams, Shepherd, Spores, Stars, Wildfire, etc. (Vos elegiste Land - Bosque.)' },
      { level:2, name:'Land Circle: Bonus Cantrip', nameEs:'Circle Bosque: Cantrip Bonus',
        desc:'Cantrip druida adicional a elegir. Los del Bosque suelen estar relacionados con la naturaleza.' },
      { level:2, name:'Natural Recovery', nameEs:'Recuperación Natural',
        desc:'1 uso por long rest, durante un short rest: recuperar slots cuya suma de niveles ≤ ½ nivel druida (Nv 2 → 1 slot Nv 1).' },
      { level:3, name:'Land Spells (Bosque)', nameEs:'Hechizos del Círculo Bosque',
        desc:'Hechizos siempre preparados (no cuentan al límite): Nv 3 → Barkskin, Spider Climb · Nv 5 → Call Lightning, Plant Growth · Nv 7 → Divination, Freedom of Movement · Nv 9 → Commune with Nature, Tree Stride.' },
      { level:4, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:4, name:'Wild Shape: nadador', nameEs:'Wild Shape mejorado',
        desc:'CR máx sube a ½. Podés tomar formas con velocidad de nado.' },
      { level:5, name:'Slots de nivel 3', nameEs:'Slots de nivel 3', desc:'Desbloqueás slots de hechizo de nivel 3.' },
      { level:6, name:'Land\'s Stride', nameEs:'Marcha del Bosque',
        desc:'(Circle Land) Inmune a daño y velocidad reducida de plantas no-mágicas. Plantas mágicas: ventaja en saves contra ellas.' },
      { level:7, name:'Slots de nivel 4', nameEs:'Slots de nivel 4', desc:'Desbloqueás slots de hechizo de nivel 4.' },
      { level:8, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:8, name:'Wild Shape: volador', nameEs:'Wild Shape volador',
        desc:'CR máx sube a 1. Podés tomar formas con velocidad de vuelo (perfecto para un Owlin!).' },
      { level:9, name:'Slots de nivel 5', nameEs:'Slots de nivel 5', desc:'Desbloqueás slots de hechizo de nivel 5.' },
      { level:10, name:'Nature\'s Ward', nameEs:'Protección de la Naturaleza',
        desc:'(Circle Land) Inmune a charm/frighten por elementales y feéricos. Inmune a venenos y enfermedades.' },
      { level:11, name:'Slots de nivel 6', nameEs:'Slots de nivel 6', desc:'Desbloqueás slots de nivel 6.' },
      { level:12, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:13, name:'Slots de nivel 7', nameEs:'Slots de nivel 7', desc:'Desbloqueás slots de nivel 7.' },
      { level:14, name:'Nature\'s Sanctuary', nameEs:'Santuario de la Naturaleza',
        desc:'(Circle Land) Bestias y plantas que te ataquen deben tirar WIS save DC tu Spell DC o no pueden hacerlo (eligen otro blanco o pierden el ataque).' },
      { level:15, name:'Slots de nivel 8', nameEs:'Slots de nivel 8', desc:'Desbloqueás slots de nivel 8.' },
      { level:16, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:17, name:'Slots de nivel 9', nameEs:'Slots de nivel 9', desc:'Desbloqueás slots de nivel 9 (máximo).' },
      { level:18, name:'Timeless Body', nameEs:'Cuerpo Atemporal', desc:'Envejecés 10 veces más lento.' },
      { level:18, name:'Beast Spells', nameEs:'Hechizos en Bestia',
        desc:'Podés lanzar hechizos en forma de Wild Shape (componentes verbales/somáticos OK, materiales solo si tu forma puede manipularlos).' },
      { level:19, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:20, name:'Archdruid', nameEs:'Archidruida',
        desc:'Wild Shape ilimitado. Podés ignorar componentes verbales, somáticos y materiales (no consumibles) de hechizos druidas.' }
    ],
    spellSaveDC:13,
    spellAtk:'+5',
    spellSlots:{ '1': 3 },
    // TODO cantrip-progression: Boyd aprende 1 cantrip nuevo a Nv 4
    // (total 3) y otro a Nv 10 (total 4). Cuando suceda en mesa,
    // descomentar/editar uno de los templates de abajo y moverlo
    // dentro del array `cantripsData`. Opciones druida no usadas:
    // Guidance, Mending, Poison Spray, Resistance, Shillelagh,
    // Magic Stone, Primal Savagery, Control Flames, Frostbite, Gust,
    // Mold Earth, Shape Water, Thunderclap, Create Bonfire.
    //
    // // Template Nv 4 (elegir uno y descomentar):
    // { name:'Guidance', nameEs:'Guía', school:'divination', shape:'1 criatura · Toque · Concentración',
    //   desc:'Concentración, 1 min. La criatura suma 1d4 a una ability check de su elección antes del fin de la duración.' },
    // // Template Nv 10 (elegir uno y descomentar):
    // { name:'Primal Savagery', nameEs:'Ferocidad Primordial', school:'transmutation', shape:'Toque, melee spell attack',
    //   damageBase:'1d10', damageType:'acid',
    //   damageScaling:{ 5:'2d10', 11:'3d10', 17:'4d10' },
    //   desc:'Acción. Toque. Spell attack. Dientes/garras crecen 1 turno.' },
    cantripsData:[
      { name:'Druidcraft', nameEs:'Druidería', school:'transmutation', shape:'30 ft',
        desc:'Acción. Hasta 30 ft. Predecir clima 24 h · hacer florecer una flor · prender o apagar un fuego pequeño · crear efecto sensorial menor. Pura utilidad.' },
      { name:'Thorn Whip', nameEs:'Látigo de Espinas', school:'transmutation', shape:'30 ft, melee spell attack',
        damageBase:'1d6', damageType:'piercing',
        damageScaling:{ 5:'2d6', 11:'3d6', 17:'4d6' },
        desc:'Acción. 30 ft. Spell attack contra criatura. Si pega, tirás al objetivo (Grande o menor) hasta 10 ft hacia vos.' }
    ],
    spellList:[
      // Nivel 1
      { name:'Entangle', nameEs:'Enredar', level:1, prepared:true, school:'conjuration', shape:'⬛ 20-ft cuadrado @ 90 ft',
        saveType:'str', halfOnSave:false,
        effect:{ casterCondition:'concentration', targetConditionOnFail:'restrained', duration:10 },
        desc:'Concentración, 10 rounds (1 min). Plantas brotan. STR save o restringidos. Repite save al final de cada turno.' },
      { name:'Cure Wounds', nameEs:'Curar Heridas', level:1, prepared:true, school:'evocation', shape:'Toque',
        desc:'Curar 1d8 + WIS mod (= 1d8+3) HP. +1d8 por slot extra.' },
      { name:'Goodberry', nameEs:'Baya Mágica', level:1, prepared:false, school:'transmutation', shape:'Auto',
        desc:'10 bayas. Cada una cura 1 HP y nutre por 1 día. Duran 24 h.' },
      { name:'Thunderwave', nameEs:'Onda Atronadora', level:1, prepared:true, school:'evocation', shape:'⬛ 15-ft cubo desde Boyd',
        damage:'2d8', damageType:'thunder', saveType:'con', halfOnSave:true,
        desc:'CON save o 2d8 thunder + empujados 10 ft. Mitad si pasan. +1d8 por slot.' },

      { name:'Faerie Fire', nameEs:'Fuego Feérico', level:1, prepared:false, school:'evocation', shape:'⬛ 20-ft cubo @ 60 ft',
        desc:'Concentración, 1 min. DEX save o iluminados: ataques contra ellos con ventaja, no pueden estar invisibles.' },
      { name:'Healing Word', nameEs:'Palabra de Sanación', level:1, prepared:true, school:'evocation', shape:'1 aliado @ 60 ft',
        desc:'Bonus Action. Curar 1d4 + WIS mod HP. +1d4 por slot.' },
      { name:'Animal Friendship', nameEs:'Amistad con Animales', level:1, prepared:false, school:'enchantment', shape:'1 bestia @ 30 ft',
        desc:'24 h. WIS save o la bestia (INT 4 o menos) se vuelve amistosa hacia vos.' },
      { name:'Charm Person', nameEs:'Encantar Persona', level:1, prepared:false, school:'enchantment', shape:'1 humanoide @ 30 ft',
        desc:'1 h. WIS save o te ve como amigo. Termina si lo dañás vos o tus aliados.' },
      { name:'Detect Magic', nameEs:'Detectar Magia', level:1, prepared:false, school:'divination', shape:'⬛ 30-ft self · ritual',
        desc:'Concentración, 10 min. Sentir presencia de magia y su escuela.' },
      { name:'Fog Cloud', nameEs:'Nube de Niebla', level:1, prepared:false, school:'conjuration', shape:'⬛ 20-ft esfera @ 120 ft',
        desc:'Concentración, 1 h. Niebla pesada bloquea visión. +1 esfera radius por slot.' },
      { name:'Speak with Animals', nameEs:'Hablar con Animales', level:1, prepared:false, school:'divination', shape:'Self · ritual',
        desc:'10 min. Podés comunicarte con bestias. Su info es limitada por su inteligencia.' },
      { name:'Longstrider', nameEs:'Zancada Larga', level:1, prepared:false, school:'transmutation', shape:'1 criatura · Toque',
        desc:'1 h. +10 ft de velocidad. +1 objetivo por slot.' },

      // Nivel 2 (desbloqueado a Nv 3)
      { name:'Moonbeam', nameEs:'Rayo Lunar', level:2, prepared:false, school:'evocation', shape:'5-ft cilindro 40-ft alto @ 120 ft · Concentración',
        damage:'2d10', damageType:'radiant', saveType:'con', halfOnSave:true,
        effect:{ casterCondition:'concentration', duration:10 },
        desc:'Concentración, 10 rounds (1 min). Criaturas que entren o empiecen turno: CON save o 2d10 radiante. Bonus action c/turno: mover el rayo 60 ft.' },
      { name:'Spike Growth', nameEs:'Crecimiento de Espinas', level:2, prepared:false, school:'transmutation', shape:'⬛ 20-ft radio @ 150 ft · Concentración',
        desc:'Concentración, 10 min. Terreno difícil. Cada 5 ft caminando: 2d4 piercing. WIS DC 15 para notarlas si no se ven.' },
      { name:'Pass Without Trace', nameEs:'Pasar sin Rastro', level:2, prepared:false, school:'abjuration', shape:'⬛ 30-ft self aura · Concentración',
        desc:'Concentración, 1 h. Vos y aliados en el aura: +10 a Stealth, sin huellas/aroma.' },
      { name:'Lesser Restoration', nameEs:'Restauración Menor', level:2, prepared:false, school:'abjuration', shape:'1 criatura · Toque',
        desc:'Curás 1 condición: blinded/deafened/paralyzed/poisoned o una enfermedad.' },
      { name:'Heat Metal', nameEs:'Metal Ardiente', level:2, prepared:false, school:'transmutation', shape:'1 objeto metal @ 60 ft · Concentración',
        desc:'Concentración, 1 min. Quien lo toque: 2d8 fuego + CON save o suelta el objeto. Bonus action c/turno para volver a quemar.' },
      { name:'Barkskin', nameEs:'Piel de Corteza', level:2, prepared:false, school:'transmutation', shape:'1 criatura · Toque · Concentración',
        alwaysPrepared:true, alwaysPreparedAt:3, circleSpell:'Land (Bosque)',
        desc:'Concentración, 1 h. Mínimo CA 16 (si tenía menos).' },
      { name:'Spider Climb', nameEs:'Trepar como Araña', level:2, prepared:false, school:'transmutation', shape:'1 criatura · Toque · Concentración',
        alwaysPrepared:true, alwaysPreparedAt:3, circleSpell:'Land (Bosque)',
        desc:'Concentración, 1 h. La criatura puede trepar paredes y techos con las manos libres, sin tirada. Velocidad de trepar = velocidad caminar.' },
      { name:'Flame Blade', nameEs:'Espada Llameante', level:2, prepared:false, school:'evocation', shape:'Self · Concentración',
        desc:'Concentración, 10 min. Espada de fuego en tu mano. Action: melee spell attack, 3d6 fuego. Ilumina 10 ft.' },
      { name:'Animal Messenger', nameEs:'Mensajero Animal', level:2, prepared:false, school:'enchantment', shape:'1 bestia chica @ 30 ft',
        desc:'24 h. Una bestia diminuta lleva un mensaje hasta 25 millas.' },

      // Nivel 3 (Nv 5)
      { name:'Call Lightning', nameEs:'Llamar Relámpago', level:3, prepared:false, school:'conjuration', shape:'⬛ 5-ft cilindro 10-ft alto · Concentración',
        alwaysPrepared:true, alwaysPreparedAt:5, circleSpell:'Land (Bosque)',
        damage:'3d10', damageType:'lightning', saveType:'dex', halfOnSave:true,
        effect:{ casterCondition:'concentration', duration:100 },
        desc:'Concentración, 100 rounds (10 min). Nube. Action c/turno: DEX save o 3d10 lightning a 1 criatura. Si afuera y stormy: +1d10.' },
      { name:'Plant Growth', nameEs:'Crecer Plantas', level:3, prepared:false, school:'transmutation', shape:'⬛ 100-ft radio @ 150 ft',
        alwaysPrepared:true, alwaysPreparedAt:5, circleSpell:'Land (Bosque)',
        desc:'1 acción o 8 h. Acción: terreno difícil 1 día. 8 h: zona enriquece 1 año, cosechas x2.' },
      { name:'Conjure Animals', nameEs:'Invocar Animales', level:3, prepared:false, school:'conjuration', shape:'@ 60 ft · Concentración',
        desc:'Concentración, 1 h. Invocás bestias: 1×CR 2, 2×CR 1, 4×CR ½, 8×CR ¼. Suben con slots mayores.' },
      { name:'Dispel Magic', nameEs:'Disipar Magia', level:3, prepared:false, school:'abjuration', shape:'1 objetivo @ 120 ft',
        desc:'Termina hechizos ≤ Nv 3 automáticamente. Mayores: spellcasting check DC 10+nivel.' },
      { name:'Sleet Storm', nameEs:'Tormenta de Aguanieve', level:3, prepared:false, school:'conjuration', shape:'⬛ 20-ft cilindro 40-ft alto @ 150 ft · Concentración',
        desc:'Concentración, 1 min. Vista bloqueada · terreno difícil · DEX save o prone al entrar.' },
      { name:'Wind Wall', nameEs:'Muro de Viento', level:3, prepared:false, school:'evocation', shape:'50-ft × 15-ft × 1-ft @ 120 ft · Concentración',
        desc:'Concentración, 1 min. Bloquea proyectiles pequeños/gases. Criaturas Tiny pueden ser pushed.' },

      // Nivel 4 (Nv 7)
      { name:'Polymorph', nameEs:'Polimorfar', level:4, prepared:false, school:'transmutation', shape:'1 criatura @ 60 ft · Concentración',
        desc:'Concentración, 1 h. WIS save o transformada en bestia de CR ≤ nivel actual (no caster). HP de la nueva forma. Termina al llegar a 0 HP en bestia.' },
      { name:'Wall of Fire', nameEs:'Muro de Fuego', level:4, prepared:false, school:'evocation', shape:'60-ft línea o 20-ft anillo · Concentración',
        desc:'Concentración, 1 min. DEX save al entrar/terminar turno: 5d8 fuego. Mitad si pasan. Un lado quema (vos elegís).' },
      { name:'Ice Storm', nameEs:'Tormenta de Hielo', level:4, prepared:false, school:'evocation', shape:'⬛ 20-ft cilindro 40-ft alto @ 300 ft',
        damage:'2d8+4d6', damageType:'cold', saveType:'dex', halfOnSave:true,
        desc:'Action. DEX save: 2d8 bludgeoning + 4d6 cold. Mitad si pasan. Terreno difícil 1 turno.' },
      { name:'Stoneskin', nameEs:'Piel de Piedra', level:4, prepared:false, school:'transmutation', shape:'1 criatura · Toque · Concentración',
        desc:'Concentración, 1 h. Resistencia a daño bludgeoning/piercing/slashing no-mágico.' },
      { name:'Dominate Beast', nameEs:'Dominar Bestia', level:4, prepared:false, school:'enchantment', shape:'1 bestia @ 60 ft · Concentración',
        desc:'Concentración, 1 min. WIS save o lo controlás telepáticamente. Re-save al recibir daño.' },
      { name:'Freedom of Movement', nameEs:'Libertad de Movimiento', level:4, prepared:false, school:'abjuration', shape:'1 criatura · Toque',
        alwaysPrepared:true, alwaysPreparedAt:7, circleSpell:'Land (Bosque)',
        desc:'1 h. Movimiento no se reduce. Inmune a paralyzed/restrained de hechizos. Puede gastar 5 ft de mov para soltarse de grapples.' },

      // Nivel 5 (Nv 9)
      { name:'Mass Cure Wounds', nameEs:'Curar Masivo', level:5, prepared:false, school:'evocation', shape:'⬛ 30-ft esfera @ 60 ft',
        desc:'Hasta 6 criaturas: 3d8 + WIS mod HP a cada una. +1d8 por slot.' },
      { name:'Insect Plague', nameEs:'Plaga de Insectos', level:5, prepared:false, school:'conjuration', shape:'⬛ 20-ft esfera @ 300 ft · Concentración',
        damage:'4d10', damageType:'piercing', saveType:'con', halfOnSave:true,
        desc:'Concentración, 10 min. Terreno difícil. CON save al entrar o end of turn: 4d10 piercing. Mitad si pasan.' },
      { name:'Tree Stride', nameEs:'Marcha del Árbol', level:5, prepared:false, school:'conjuration', shape:'Self · Concentración',
        alwaysPrepared:true, alwaysPreparedAt:9, circleSpell:'Land (Bosque)',
        desc:'Concentración, 1 min. 1×turno: 5 ft acción para entrar en árbol vivo y salir por otro a 500 ft.' },
      { name:'Wall of Stone', nameEs:'Muro de Piedra', level:5, prepared:false, school:'evocation', shape:'@ 120 ft · Concentración',
        desc:'Concentración, 10 min. Crear muro de piedra hasta 60-ft × 20-ft × 6-in. Permanente si sostenés la concentración hasta el final.' },
      { name:'Commune with Nature', nameEs:'Comunión con la Naturaleza', level:5, prepared:false, school:'divination', shape:'Self · ritual',
        alwaysPrepared:true, alwaysPreparedAt:9, circleSpell:'Land (Bosque)',
        desc:'1 min. Conocer 3 hechos del terreno a 3 millas: territorio, agua, plantas, asentamientos, etc.' },
      { name:'Reincarnate', nameEs:'Reencarnar', level:5, prepared:false, school:'transmutation', shape:'1 criatura muerta · Toque',
        desc:'1 h. Una criatura muerta hace ≤ 10 días vuelve a la vida en un cuerpo nuevo de raza aleatoria.' },

      // Nivel 6 (Nv 11)
      { name:'Heal', nameEs:'Sanar', level:6, prepared:false, school:'evocation', shape:'1 criatura @ 60 ft',
        desc:'70 HP curados + cura blinded/deafened/cualquier enfermedad. +10 HP por slot extra.' },
      { name:'Sunbeam', nameEs:'Rayo Solar', level:6, prepared:false, school:'evocation', shape:'5-ft × 60-ft línea · Concentración',
        damage:'6d8', damageType:'radiant', saveType:'con', halfOnSave:true,
        desc:'Concentración, 1 min. Action c/turno: DEX save o 6d8 radiante + blinded hasta tu próx turno.' },
      { name:'Wall of Thorns', nameEs:'Muro de Espinas', level:6, prepared:false, school:'conjuration', shape:'@ 120 ft · Concentración',
        damage:'7d8', damageType:'slashing',
        desc:'Concentración, 10 min. 60-ft × 10-ft × 5-ft muro. Pasar: 7d8 slashing. Iniciar/end turn adentro: 7d8 piercing.' },
      { name:'Heroes\' Feast', nameEs:'Festín de Héroes', level:6, prepared:false, school:'conjuration', shape:'30-ft @ 30 ft',
        desc:'24 h. Festín para 12 criaturas. Comer: +2d10 HP max, ventaja en WIS saves, inmune a poison/frightened.' },

      // Nivel 7 (Nv 13)
      { name:'Fire Storm', nameEs:'Tormenta de Fuego', level:7, prepared:false, school:'evocation', shape:'10 cubos de 10-ft @ 150 ft',
        desc:'Action. DEX save o 7d10 fuego. Mitad si pasan. Vos elegís cuáles cubos no se incendian.' },
      { name:'Regenerate', nameEs:'Regenerar', level:7, prepared:false, school:'transmutation', shape:'1 criatura · Toque',
        desc:'1 h. Curar 4d8+15. Regenera miembros perdidos. Curar 1 HP/min mientras dura.' },
      { name:'Plane Shift', nameEs:'Cambio de Plano', level:7, prepared:false, school:'conjuration', shape:'Toque',
        desc:'Action. Hasta 8 criaturas o 1 enemigo (CHA save) son enviadas a otro plano de existencia.' },
      { name:'Reverse Gravity', nameEs:'Invertir Gravedad', level:7, prepared:false, school:'transmutation', shape:'⬛ 50-ft cilindro 100-ft alto @ 100 ft · Concentración',
        desc:'Concentración, 1 min. Gravedad invertida en el área. Todo lo no atado cae hacia arriba.' },

      // Nivel 8 (Nv 15)
      { name:'Earthquake', nameEs:'Terremoto', level:8, prepared:false, school:'evocation', shape:'⬛ 100-ft radio @ 500 ft · Concentración',
        desc:'Concentración, 1 min. Terreno tiembla: prone, fissures, derrumbes, daño a estructuras.' },
      { name:'Animal Shapes', nameEs:'Formas Animales', level:8, prepared:false, school:'transmutation', shape:'30 ft · Concentración',
        desc:'Concentración, 24 h. Hasta 1 criatura willing por slot: forma de bestia CR ≤ 4. HP de la bestia.' },
      { name:'Sunburst', nameEs:'Estallido Solar', level:8, prepared:false, school:'evocation', shape:'⬛ 60-ft esfera @ 150 ft',
        desc:'Action. CON save o 12d6 radiante + blinded 1 min. Mitad si pasan, no blinded.' },
      { name:'Control Weather', nameEs:'Controlar Clima', level:8, prepared:false, school:'transmutation', shape:'5-mile radius · Concentración',
        desc:'Concentración, 8 h. Cambiás clima de la zona en 1d4×10 min: temperatura, viento, precipitación.' },

      // Nivel 9 (Nv 17)
      { name:'Foresight', nameEs:'Presciencia', level:9, prepared:false, school:'divination', shape:'1 criatura · Toque',
        desc:'8 h. Ventaja en todos los ataques, ability checks y saves. Otros tienen desventaja al atacarla. Inmune a surprised.' },
      { name:'Shapechange', nameEs:'Cambio de Forma', level:9, prepared:false, school:'transmutation', shape:'Self · Concentración',
        desc:'Concentración, 1 h. Te convertís en cualquier criatura CR ≤ tu nivel (no de origen mítico). HP/stats nuevos.' },
      { name:'Storm of Vengeance', nameEs:'Tormenta de Venganza', level:9, prepared:false, school:'conjuration', shape:'⬛ 360-ft cilindro @ vista · Concentración',
        desc:'Concentración, 1 min. Round 1: 2d6 thunder + STR save o deafened. R2: hailstones 1d10 cold. R3: lluvia 1d6 acid. R4-10: rayos 10d6 lightning.' },
      { name:'True Resurrection', nameEs:'Resurrección Verdadera', level:9, prepared:false, school:'necromancy', shape:'1 criatura muerta · Toque',
        desc:'1 h. Revive una criatura muerta hace ≤ 200 años. Cura todo. Sin componente material costoso, no funciona.' }
    ]
  },
  esdas: {
    className:'Wizard',
    equipment:[
      {itemId:'dagger',  equipped:true},
      {itemId:'unarmed', equipped:true}
    ],
    saveProfs:['int','wis'],
    skillProfs:[
      {name:'Arcana',nameEs:'Arcanos',ability:'int'},
      {name:'Investigation',nameEs:'Investigación',ability:'int'},
      {name:'History',nameEs:'Historia',ability:'int'},
      {name:'Insight',nameEs:'Perspicacia',ability:'wis'}
    ],
    campaignNotes:[
      { type:'warning', title:'Camino arcano — regla de campaña',
        desc:'Esdas todavía no se comprometió con una Escuela de Magia. Puede APRENDER hechizos de cualquier escuela libremente, pero hasta que elija una Arcane Tradition paga el costo:\n\n• Pierde el feature de Arcane Tradition de nivel 2 (Sculpt Spells, Hypnotic Gaze, Portent, Minor Conjuration, etc.) hasta comprometerse.\n• Pierde el Savant de su escuela (mitad de oro y tiempo para copiar scrolls de esa escuela al spellbook).\n• Sus CANTRIPS DE DAÑO NO ESCALAN: Firebolt y Ray of Frost se quedan en 1 dado de daño hasta el nivel 17, en lugar de subir a 2d a Nv 5, 3d a Nv 11, 4d a Nv 17. Los demás cantrips no se ven afectados.\n\nCuando un evento narrativo lo empuje a comprometerse (un mentor, un descubrimiento profundo, una crisis), elige su escuela definitiva y recupera todos los bonos perdidos + la progresión normal de wizard a partir de ese punto.' }
    ],
    resources:[
      { key:'arcane-recovery', name:'Arcane Recovery', nameEs:'Recuperación Arcana', kind:'uses', restoresOn:'long',
        desc:'1 uso por long rest, durante un short rest: recuperar slots cuya suma de niveles ≤ ½ nivel wizard redondeado hacia arriba.' }
    ],
    levelFeatures:[
      { level:1, name:'Spellcasting (INT)', nameEs:'Lanzamiento de Hechizos (INT)',
        desc:'Full caster. Spell save DC = 8+prof+INT · Spell attack = prof+INT. Preparás INT mod + nivel wizard hechizos del spellbook por long rest. Necesitás spellbook + componente material o foco arcano. Spellbook arranca con 6 hechizos al Nv 1 y suma 2 por nivel.' },
      { level:1, name:'Arcane Recovery', nameEs:'Recuperación Arcana',
        desc:'Una vez por long rest, durante un short rest, recuperar slots cuya suma de niveles ≤ ½ nivel wizard redondeado hacia arriba.' },
      // TODO subclass: cuando Esdas se comprometa con una escuela, agregar
      // entries de level:2, 6, 10, 14 con los features de la Arcane
      // Tradition elegida. La función commitToSchool() en este archivo
      // ya marca el flag, pero los features de la escuela específica
      // (Sculpt Spells de Evocation, Hypnotic Gaze de Enchantment, Portent
      // de Divination, Minor Conjuration de Conjuration, etc.) hay que
      // sumarlos manualmente al levelFeatures de esdas.
      // Cuando se comprometa, también el escalado de cantrips de daño se
      // desbloquea automáticamente (getCantripDamageDice ya lo respeta).
      { level:2, name:'Arcane Tradition (indecisa)', nameEs:'Tradición Arcana (sin comprometer)',
        desc:'Normalmente a Nv 2 el wizard elige su escuela definitiva (Evocation, Enchantment, Divination, Illusion, Abjuration, Conjuration, Necromancy, Transmutation, War Magic, Bladesinging, etc.). Esdas se mantiene generalista — ver "Camino arcano" arriba.' },
      { level:3, name:'Slots de nivel 2', nameEs:'Slots de nivel 2',
        desc:'Desbloqueás slots de hechizo de nivel 2. 2 slots a Nv 3. Hechizos de nivel 2 disponibles para aprender.' },
      { level:4, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:5, name:'Slots de nivel 3', nameEs:'Slots de nivel 3',
        desc:'Desbloqueás slots de hechizo de nivel 3 (Fireball, Counterspell, etc.). Cantrips de daño suben a 2 dados (BLOQUEADO mientras no elija escuela).' },
      { level:6, name:'Tradition Feature', nameEs:'Feature de Tradición',
        desc:'Habilidad de subclase a Nv 6 (ej: Potent Cantrip de Evocation, Instinctive Charm de Enchantment). BLOQUEADO mientras no elija escuela.' },
      { level:7, name:'Slots de nivel 4', nameEs:'Slots de nivel 4', desc:'Desbloqueás slots de hechizo de nivel 4.' },
      { level:8, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:9, name:'Slots de nivel 5', nameEs:'Slots de nivel 5', desc:'Telequinesis real (5th-level Telekinesis) ahora disponible.' },
      { level:10, name:'Tradition Feature', nameEs:'Feature de Tradición', desc:'Segundo feature de subclase. BLOQUEADO mientras no elija.' },
      { level:11, name:'Slots de nivel 6', nameEs:'Slots de nivel 6',
        desc:'Cantrips de daño suben a 3 dados (BLOQUEADO mientras no elija escuela).' },
      { level:12, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:13, name:'Slots de nivel 7', nameEs:'Slots de nivel 7', desc:'Desbloqueás slots de nivel 7.' },
      { level:14, name:'Tradition Feature', nameEs:'Feature de Tradición', desc:'Tercer feature de subclase. BLOQUEADO.' },
      { level:15, name:'Slots de nivel 8', nameEs:'Slots de nivel 8', desc:'Desbloqueás slots de nivel 8.' },
      { level:16, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:17, name:'Slots de nivel 9', nameEs:'Slots de nivel 9',
        desc:'Desbloqueás Wish y otros 9th. Cantrips de daño suben a 4 dados (BLOQUEADO).' },
      { level:18, name:'Spell Mastery', nameEs:'Maestría de Hechizo',
        desc:'Elegís 1 hechizo de Nv 1 y 1 de Nv 2 del spellbook. Podés lanzar esos hechizos a su nivel base sin gastar slot.' },
      { level:19, name:'ASI', nameEs:'Mejora de Stats', desc:'+2/+1+1/feat.' },
      { level:20, name:'Signature Spells', nameEs:'Hechizos Insignia',
        desc:'Elegís 2 hechizos de Nv 3 del spellbook. Siempre los tenés preparados, y podés lanzar cada uno 1 vez por short/long rest sin gastar slot.' }
    ],
    spellSaveDC:13,
    spellAtk:'+5',
    spellSlots:{ '1': 3 },
    // TODO cantrip-progression: Esdas aprende 1 cantrip nuevo a Nv 4
    // (total 4) y otro a Nv 10 (total 5). Cuando suceda en mesa,
    // descomentar/editar template y moverlo a `cantripsData`.
    // Opciones wizard no usadas: Acid Splash, Light, Minor Illusion,
    // Poison Spray, Shocking Grasp, True Strike, Mind Sliver, Booming
    // Blade, Green-Flame Blade, Sword Burst, Toll the Dead, Frostbite,
    // Lightning Lure, Control Flames, Dancing Lights, Message, Prestidigitation.
    //
    // NOTA: si Esdas se compromete con una escuela, los cantrips de daño
    // nuevos que aprenda tendrán damage scaling normal automáticamente
    // (getCantripDamageDice ya lo respeta).
    //
    // // Template Nv 4 (utility, sin daño):
    // { name:'Prestidigitation', nameEs:'Prestidigitación', school:'transmutation', shape:'10 ft',
    //   desc:'Acción. 1 h. Efecto mágico menor: ensuciar/limpiar, prender/apagar vela, hacer sonido, etc.' },
    // // Template Nv 10 (daño con scaling):
    // { name:'Mind Sliver', nameEs:'Esquirla Mental', school:'enchantment', shape:'60 ft',
    //   damageBase:'1d6', damageType:'psychic',
    //   damageScaling:{ 5:'2d6', 11:'3d6', 17:'4d6' },
    //   desc:'Acción. 60 ft. INT save. Daño psíquico + resta 1d4 al próximo save antes del fin de tu próximo turno.' },
    cantripsData:[
      { name:'Firebolt', nameEs:'Rayo de Fuego', school:'evocation', shape:'120 ft, ranged spell attack',
        damageBase:'1d10', damageType:'fire',
        damageScaling:{ 5:'2d10', 11:'3d10', 17:'4d10' },
        desc:'Acción. 120 ft. Spell attack. Si pega objeto inflamable no sostenido, se prende.\n⚠ Escalado BLOQUEADO mientras Esdas no se comprometa con una escuela.' },
      { name:'Ray of Frost', nameEs:'Rayo de Escarcha', school:'evocation', shape:'60 ft, ranged spell attack',
        damageBase:'1d8', damageType:'cold',
        damageScaling:{ 5:'2d8', 11:'3d8', 17:'4d8' },
        desc:'Acción. 60 ft. Spell attack. Si pega: daño cold + el objetivo pierde 10 ft de velocidad hasta el inicio de tu próximo turno.\n⚠ Escalado BLOQUEADO mientras Esdas no se comprometa con una escuela.' },
      { name:'Mage Hand', nameEs:'Mano Mágica', school:'conjuration', shape:'30 ft',
        desc:'Acción. Mano espectral invisible flotante. Manipula objetos hasta 10 lb, abre puertas/cofres, vierte líquidos. No puede atacar ni activar magia. Dura 1 minuto. Esdas lo usa como base de su "telekinesis incompleta" — los límites del cantrip frustran sus intentos de hacerlo más fuerte.' }
    ],
    spellList:[
      { name:'Magic Missile', nameEs:'Misil Mágico', level:1, prepared:true, school:'evocation', shape:'3 dardos @ 120 ft',
        damage:'3d4+3', damageType:'force',
        desc:'Acción. 120 ft. 3 dardos de 1d4+1 force cada uno. Sin save ni ataque — siempre pegan al objetivo elegido (mismo o distintos). +1 dardo por slot extra.' },
      { name:'Shield', nameEs:'Escudo', level:1, prepared:true, school:'abjuration', shape:'Reaction · Auto',
        desc:'Reaction al ser blanco de un ataque o de Magic Missile: +5 CA hasta tu próximo turno + niega Magic Missile completamente.' },
      { name:'Mage Armor', nameEs:'Armadura de Mago', level:1, prepared:true, school:'abjuration', shape:'1 criatura · Toque',
        desc:'Acción. Una criatura sin armadura: CA = 13 + DEX mod por 8 horas. Probablemente activa sobre Esdas, dándole CA 15.' },
      { name:'Ice Knife', nameEs:'Cuchillo de Hielo', level:1, prepared:true, school:'conjuration', shape:'1 obj + ⬛ 5-ft esfera @ 60 ft',
        damage:'1d10', damageType:'piercing',
        desc:'Acción. Spell attack +5 contra una criatura a 60 ft. Si pega: 1d10 perforante (el cuchillo de hielo). Pegue o falle, el cuchillo explota: criaturas a 5 ft del objetivo tiran DEX save (DC 13) o 2d6 cold. +1d6 cold por slot extra. NUEVO — frost.' },
      { name:"Tasha’s Hideous Laughter", nameEs: "’Risa Espantosa de Tasha’", level:1, prepared:true, school:"enchantment", shape:"1 criatura @ 30 ft",
        saveType:"wis", halfOnSave:false,
        effect:{ casterCondition:"concentration", targetConditionOnFail:"incapacitated", duration:10 },
        desc:"Acción. Concentración, 1 min. WIS save (DC 13) o la criatura cae al piso riendo: prone + incapacitated por la duración. Repite save al final de cada turno o cuando reciba daño. Inmunes: criaturas sin INT 5+ o que no puedan oír. NUEVO — control mental." },
      { name:'Burning Hands', nameEs:'Manos Ardientes', level:1, prepared:false, school:'evocation', shape:'⬛ 15-ft cono desde Esdas',
        damage:'3d6', damageType:'fire', saveType:'dex', halfOnSave:true,
        desc:'15-ft cono emanando de Esdas. DEX save (DC 13) o 3d6 fuego. Mitad si pasan. Prende objetos inflamables no sostenidos. +1d6 por slot extra.' },
      { name:'Sleep', nameEs:'Sueño', level:1, prepared:false, school:'enchantment', shape:'⬛ 20-ft esfera @ 90 ft',
        desc:'Acción. Tirá 5d8 HP. Las criaturas afectadas en una esfera de 20 ft caen dormidas, de menor HP primero, hasta agotar el total. Inmunes: no-muertos, criaturas inmunes a charm. +2d8 por slot extra.' },
      { name:'Detect Magic', nameEs:'Detectar Magia', level:1, prepared:false, school:'divination', shape:'30-ft self · ritual',
        desc:'Concentración, 10 min. Como wizard, ritual sin gastar slot.' },
      { name:'Find Familiar', nameEs:'Encontrar Familiar', level:1, prepared:false, school:'conjuration', shape:'1 h de ritual',
        desc:'Invocás un familiar (rata, gato, cuervo, etc.). Telepatía 100 ft. Action para ver/oír por sus ojos.' },
      { name:'Feather Fall', nameEs:'Caída de Pluma', level:1, prepared:false, school:'transmutation', shape:'5 criaturas @ 60 ft · Reaction',
        desc:'Reaction al caer. Velocidad de caída 60 ft/round, sin daño.' },
      { name:'Charm Person', nameEs:'Encantar Persona', level:1, prepared:false, school:'enchantment', shape:'1 humanoide @ 30 ft',
        desc:'1 h. WIS save o te ve como amigo. Termina si lo dañás vos o aliados.' },
      { name:'Identify', nameEs:'Identificar', level:1, prepared:false, school:'divination', shape:'1 objeto · Toque · ritual',
        desc:'1 min. Conocer propiedades mágicas, cargas y comandos de un objeto.' },
      { name:'Grease', nameEs:'Grasa', level:1, prepared:false, school:'conjuration', shape:'⬛ 10-ft cuadrado @ 60 ft',
        desc:'1 min. Terreno difícil. Quien entra/empieza turno: DEX save o prone.' },
      { name:'Disguise Self', nameEs:'Disfrazarte', level:1, prepared:false, school:'illusion', shape:'Self',
        desc:'1 h. Apariencia cambiada (no físicamente). Investigation DC vs Spell DC para detectar.' },

      // Nivel 2 (desbloqueado a Nv 3)
      { name:'Misty Step', nameEs:'Paso Nebuloso', level:2, prepared:false, school:'conjuration', shape:'Self · Bonus Action',
        desc:'Bonus Action. Teleport 30 ft a un lugar que puedas ver.' },
      { name:'Hold Person', nameEs:'Sostener Persona', level:2, prepared:false, school:'enchantment', shape:'1 humanoide @ 60 ft · Concentración',
        saveType:'wis', halfOnSave:false,
        effect:{ casterCondition:'concentration', targetConditionOnFail:'paralyzed', duration:10 },
        desc:'Concentración, 1 min. WIS save o paralyzed. Repite save al fin de cada turno. +1 objetivo por slot.' },
      { name:'Web', nameEs:'Telaraña', level:2, prepared:false, school:'conjuration', shape:'⬛ 20-ft cubo @ 60 ft · Concentración',
        desc:'Concentración, 1 h. DEX save al entrar o restrained. STR check vs Spell DC para liberarse.' },
      { name:'Mirror Image', nameEs:'Imagen Especular', level:2, prepared:false, school:'illusion', shape:'Self',
        desc:'1 min. 3 duplicados. Atacantes tiran d20: 6+ pegan a un duplicado en vez. Cada hit destruye uno.' },
      { name:'Scorching Ray', nameEs:'Rayo Abrasador', level:2, prepared:false, school:'evocation', shape:'3 rayos @ 120 ft',
        damage:'2d6', damageType:'fire',
        desc:'3 rayos. Spell attack por cada uno: 2d6 fuego. +1 rayo por slot. 🔥' },
      { name:'Levitate', nameEs:'Levitar', level:2, prepared:false, school:'transmutation', shape:'1 criatura/obj @ 60 ft · Concentración',
        desc:'Concentración, 10 min. Sube 20 ft. CON save si no quiere. Telekinesis vertical básica.' },
      { name:'Invisibility', nameEs:'Invisibilidad', level:2, prepared:false, school:'illusion', shape:'1 criatura · Toque · Concentración',
        desc:'Concentración, 1 h. Invisible hasta atacar o lanzar hechizo. +1 objetivo por slot.' },
      { name:'Shatter', nameEs:'Romper', level:2, prepared:false, school:'evocation', shape:'⬛ 10-ft esfera @ 60 ft',
        damage:'3d8', damageType:'thunder', saveType:'con', halfOnSave:true,
        desc:'CON save o 3d8 thunder. Mitad si pasan. Constructs: desventaja en save.' },
      { name:'Suggestion', nameEs:'Sugestión', level:2, prepared:false, school:'enchantment', shape:'1 criatura @ 30 ft · Concentración',
        desc:'Concentración, 8 h. WIS save o cumple sugestión razonable.' },
      { name:'Phantasmal Force', nameEs:'Fuerza Fantasmal', level:2, prepared:false, school:'illusion', shape:'1 criatura @ 60 ft · Concentración',
        desc:'Concentración, 1 min. INT save o ilusión personal. La víctima recibe 1d6 psychic/turno mientras crea.' },
      { name:'Blur', nameEs:'Borrón', level:2, prepared:false, school:'illusion', shape:'Self · Concentración',
        desc:'Concentración, 1 min. Ataques contra vos con desventaja (salvo blindsight/truesight).' },
      { name:'Knock', nameEs:'Llamar', level:2, prepared:false, school:'transmutation', shape:'1 objeto @ 60 ft',
        desc:'Abre puerta/cofre/ventana cerrada mágicamente. Ruido fuerte audible a 300 ft.' },
      { name:'Crown of Madness', nameEs:'Corona de Locura', level:2, prepared:false, school:'enchantment', shape:'1 humanoide @ 120 ft · Concentración',
        desc:'Concentración, 1 min. WIS save o lo controlás: usa su action para atacar a una criatura de tu elección.' },

      // Nivel 3 (desbloqueado a Nv 5)
      { name:'Fireball', nameEs:'Bola de Fuego', level:3, prepared:false, school:'evocation', shape:'⬛ 20-ft esfera @ 150 ft',
        damage:'8d6', damageType:'fire', saveType:'dex', halfOnSave:true,
        desc:'DEX save o 8d6 fuego. Mitad si pasan. Prende todo inflamable. +1d6 por slot. 🔥' },
      { name:'Lightning Bolt', nameEs:'Rayo', level:3, prepared:false, school:'evocation', shape:'5-ft × 100-ft línea',
        damage:'8d6', damageType:'lightning', saveType:'dex', halfOnSave:true,
        desc:'DEX save o 8d6 lightning. Mitad si pasan. +1d6 por slot.' },
      { name:'Counterspell', nameEs:'Contrahechizo', level:3, prepared:false, school:'abjuration', shape:'1 caster @ 60 ft · Reaction',
        desc:'Reaction al ver casting. Auto-anula hechizos ≤ Nv 3. Mayores: ability check DC 10+nivel.' },
      { name:'Fly', nameEs:'Volar', level:3, prepared:false, school:'transmutation', shape:'1 criatura · Toque · Concentración',
        desc:'Concentración, 10 min. Velocidad de vuelo 60 ft.' },
      { name:'Haste', nameEs:'Apresurar', level:3, prepared:false, school:'transmutation', shape:'1 criatura @ 30 ft · Concentración',
        desc:'Concentración, 1 min. Velocidad doble, +2 CA, ventaja DEX saves, 1 acción extra. Al terminar: incapacitada 1 turno.' },
      { name:'Slow', nameEs:'Lentitud', level:3, prepared:false, school:'transmutation', shape:'⬛ 40-ft cubo @ 120 ft · Concentración',
        desc:'Concentración, 1 min. Hasta 6 criaturas. WIS save o velocidad mitad, -2 CA y DEX saves, sin Bonus Action.' },
      { name:'Hypnotic Pattern', nameEs:'Patrón Hipnótico', level:3, prepared:false, school:'illusion', shape:'⬛ 30-ft cubo @ 120 ft',
        desc:'1 min. WIS save o charmed + incapacitated. Termina si recibe daño o aliado lo despierta.' },
      { name:'Fear', nameEs:'Miedo', level:3, prepared:false, school:'illusion', shape:'⬛ 30-ft cono desde Esdas · Concentración',
        desc:'Concentración, 1 min. WIS save o frightened: huye usando Dash. Repite save al fin de turno si no ve la fuente.' },
      { name:'Major Image', nameEs:'Imagen Mayor', level:3, prepared:false, school:'illusion', shape:'⬛ 20-ft cubo @ 120 ft · Concentración',
        desc:'Concentración, 10 min. Ilusión sensorial (vista, sonido, olor, temperatura). Investigation DC vs Spell DC para detectar.' },
      { name:'Sleet Storm', nameEs:'Tormenta de Aguanieve', level:3, prepared:false, school:'conjuration', shape:'⬛ 20-ft cilindro 40-ft alto @ 150 ft · Concentración',
        desc:'Concentración, 1 min. Vista bloqueada · terreno difícil · DEX save o prone. ❄' },
      { name:'Animate Dead', nameEs:'Animar Muerto', level:3, prepared:false, school:'necromancy', shape:'1 cadáver · Toque',
        desc:'1 min. Cadáver Medium se vuelve zombie o skeleton bajo tu control. Re-asumir control: castear de nuevo dentro de 24 h.' },

      // Nivel 4 (desbloqueado a Nv 7)
      { name:'Greater Invisibility', nameEs:'Invisibilidad Mayor', level:4, prepared:false, school:'illusion', shape:'1 criatura · Toque · Concentración',
        desc:'Concentración, 1 min. Invisible aunque ataque/cante.' },
      { name:'Polymorph', nameEs:'Polimorfar', level:4, prepared:false, school:'transmutation', shape:'1 criatura @ 60 ft · Concentración',
        desc:'Concentración, 1 h. WIS save o bestia CR ≤ nivel. HP de la bestia. Termina al llegar a 0 HP en bestia.' },
      { name:'Dimension Door', nameEs:'Puerta Dimensional', level:4, prepared:false, school:'conjuration', shape:'Self + 1 willing @ 500 ft',
        desc:'Acción. Teletransportarte (+1 criatura willing tocándote) hasta 500 ft a lugar conocido.' },
      { name:'Wall of Fire', nameEs:'Muro de Fuego', level:4, prepared:false, school:'evocation', shape:'60-ft × 20-ft o anillo · Concentración',
        desc:'Concentración, 1 min. DEX save: 5d8 fuego al entrar/start turn. Mitad si pasan. Un lado quema (elegís).' },
      { name:'Banishment', nameEs:'Destierro', level:4, prepared:false, school:'abjuration', shape:'1 criatura @ 60 ft · Concentración',
        desc:'Concentración, 1 min. CHA save o desterrada a Demiplano. Si extraplanar, sin save adicional, no vuelve.' },
      { name:'Stoneskin', nameEs:'Piel de Piedra', level:4, prepared:false, school:'transmutation', shape:'1 criatura · Toque · Concentración',
        desc:'Concentración, 1 h. Resistencia a daño bludgeoning/piercing/slashing no-mágico.' },
      { name:'Ice Storm', nameEs:'Tormenta de Hielo', level:4, prepared:false, school:'evocation', shape:'⬛ 20-ft cilindro 40-ft alto @ 300 ft',
        damage:'2d8+4d6', damageType:'cold', saveType:'dex', halfOnSave:true,
        desc:'DEX save: 2d8 bludgeoning + 4d6 cold. Mitad si pasan. Terreno difícil 1 turno. ❄' },
      { name:'Black Tentacles', nameEs:'Tentáculos Negros', level:4, prepared:false, school:'conjuration', shape:'⬛ 20-ft cuadrado @ 90 ft · Concentración',
        desc:'Concentración, 1 min. DEX save al entrar/start turn: 3d6 bludgeoning + restrained. STR/DEX check vs Spell DC para liberarse.' },

      // Nivel 5 (desbloqueado a Nv 9) — TELEKINESIS REAL ★
      { name:'Telekinesis', nameEs:'Telequinesis', level:5, prepared:false, school:'transmutation', shape:'@ 60 ft · Concentración',
        desc:'Concentración, 10 min. ★ Action cada turno: mover criatura Huge o menor 30 ft (STR save vs Spell DC), o manipular objetos 1000 lb. La forma definitiva de la "telekinesis incompleta" de Esdas.' },
      { name:'Cone of Cold', nameEs:'Cono de Frío', level:5, prepared:false, school:'evocation', shape:'⬛ 60-ft cono desde Esdas',
        desc:'CON save o 8d8 cold. Mitad si pasan. Criaturas muertas se vuelven estatuas de hielo. ❄ +1d8 por slot.' },
      { name:'Wall of Force', nameEs:'Muro de Fuerza', level:5, prepared:false, school:'evocation', shape:'@ 120 ft · Concentración',
        desc:'Concentración, 10 min. Plano de 10×10 paneles (×10 ft) o esfera 10-ft radio. Impenetrable salvo Disintegrate.' },
      { name:'Hold Monster', nameEs:'Sostener Monstruo', level:5, prepared:false, school:'enchantment', shape:'1 criatura @ 90 ft · Concentración',
        desc:'Concentración, 1 min. WIS save o paralyzed. Cualquier criatura (no solo humanoide). +1 objetivo por slot.' },
      { name:'Dominate Person', nameEs:'Dominar Persona', level:5, prepared:false, school:'enchantment', shape:'1 humanoide @ 60 ft · Concentración',
        desc:'Concentración, 1 min. WIS save o telepatía + control absoluto. Re-save al recibir daño.' },
      { name:'Animate Objects', nameEs:'Animar Objetos', level:5, prepared:false, school:'transmutation', shape:'10 objetos @ 120 ft · Concentración',
        desc:'Concentración, 1 min. Hasta 10 objetos no-mágicos cobran vida y luchan por vos. Stats según tamaño.' },
      { name:'Wall of Stone', nameEs:'Muro de Piedra', level:5, prepared:false, school:'evocation', shape:'@ 120 ft · Concentración',
        desc:'Concentración, 10 min. Crea muro 60-ft × 20-ft × 6-in. Permanente si la concentración se sostiene hasta el final.' },

      // Nivel 6 (desbloqueado a Nv 11)
      { name:'Disintegrate', nameEs:'Desintegrar', level:6, prepared:false, school:'transmutation', shape:'1 criatura/obj @ 60 ft',
        desc:'DEX save o 10d6 + 40 force. Si baja a 0 HP, polvo. Destruye Wall of Force.' },
      { name:'Globe of Invulnerability', nameEs:'Globo de Invulnerabilidad', level:6, prepared:false, school:'abjuration', shape:'⬛ 10-ft esfera self · Concentración',
        desc:'Concentración, 1 min. Hechizos ≤ Nv 5 no afectan nada dentro. +1 nivel por slot extra.' },
      { name:'Chain Lightning', nameEs:'Rayo en Cadena', level:6, prepared:false, school:'evocation', shape:'1 + 3 criaturas @ 150 ft',
        desc:'DEX save. Objetivo principal + 3 más a 30 ft: 10d8 lightning. Mitad si pasan. +1 objetivo por slot.' },
      { name:'True Seeing', nameEs:'Ver Verdadero', level:6, prepared:false, school:'divination', shape:'1 criatura · Toque',
        desc:'1 h. Verdadera visión: ve a través de invisibilidad, ilusiones, planos etéreos. 120 ft de Darkvision.' },
      { name:'Mass Suggestion', nameEs:'Sugestión Masiva', level:6, prepared:false, school:'enchantment', shape:'12 criaturas @ 60 ft',
        desc:'24 h. Hasta 12 criaturas: WIS save o cumplen sugestión razonable.' },

      // Nivel 7 (desbloqueado a Nv 13)
      { name:'Teleport', nameEs:'Teletransportar', level:7, prepared:false, school:'conjuration', shape:'10 criaturas willing · Toque',
        desc:'Action. Vos + 8 criaturas a un destino conocido. Margen de error según familiaridad.' },
      { name:'Plane Shift', nameEs:'Cambio de Plano', level:7, prepared:false, school:'conjuration', shape:'8 willing / 1 enemy · Toque',
        desc:'Hasta 8 willing a otro plano. O 1 enemigo CHA save o desterrado.' },
      { name:'Finger of Death', nameEs:'Dedo de la Muerte', level:7, prepared:false, school:'necromancy', shape:'1 criatura @ 60 ft',
        desc:'CON save o 7d8+30 necrotic. Mitad si pasan. Humanoides que mueren así se vuelven zombies bajo tu control.' },
      { name:'Reverse Gravity', nameEs:'Invertir Gravedad', level:7, prepared:false, school:'transmutation', shape:'⬛ 50-ft cilindro 100-ft alto @ 100 ft · Concentración',
        desc:'Concentración, 1 min. Gravedad invertida. Todo cae para arriba.' },
      { name:'Forcecage', nameEs:'Jaula de Fuerza', level:7, prepared:false, school:'evocation', shape:'⬛ 20-ft cubo @ 100 ft',
        desc:'1 h. Jaula de fuerza impenetrable. Criaturas adentro: CHA save para escapar con teletransporte, sino atrapadas.' },

      // Nivel 8 (Nv 15)
      { name:'Power Word Stun', nameEs:'Palabra: Aturdir', level:8, prepared:false, school:'enchantment', shape:'1 criatura ≤ 150 HP @ 60 ft',
        desc:'Sin save. Si HP ≤ 150: stunned. Repite CON save al fin de turno.' },
      { name:'Dominate Monster', nameEs:'Dominar Monstruo', level:8, prepared:false, school:'enchantment', shape:'1 criatura @ 60 ft · Concentración',
        desc:'Concentración, 1 h. WIS save o telepatía + control absoluto. Cualquier criatura.' },
      { name:'Mind Blank', nameEs:'Mente en Blanco', level:8, prepared:false, school:'abjuration', shape:'1 criatura · Toque',
        desc:'24 h. Inmunidad a psychic, charm, lectura de mente, divinación.' },
      { name:'Sunburst', nameEs:'Estallido Solar', level:8, prepared:false, school:'evocation', shape:'⬛ 60-ft esfera @ 150 ft',
        desc:'CON save o 12d6 radiante + blinded 1 min. Mitad si pasan.' },
      { name:'Maze', nameEs:'Laberinto', level:8, prepared:false, school:'conjuration', shape:'1 criatura @ 60 ft · Concentración',
        desc:'Concentración, 10 min. La criatura es enviada a un laberinto demiplanar. INT check DC 20 cada turno para escapar.' },

      // Nivel 9 (Nv 17)
      { name:'Wish', nameEs:'Deseo', level:9, prepared:false, school:'conjuration', shape:'Self',
        desc:'★ El hechizo más poderoso. Duplicar cualquier hechizo ≤ Nv 8, o efectos masivos (curar 20 criaturas 700 HP, etc.). Riesgos si pedís algo más.' },
      { name:'Meteor Swarm', nameEs:'Lluvia de Meteoros', level:9, prepared:false, school:'evocation', shape:'4 × ⬛ 40-ft esferas @ 1 mile',
        desc:'4 meteoros en 4 puntos. DEX save: 20d6 fuego + 20d6 bludgeoning. Mitad si pasan. 🔥' },
      { name:'Time Stop', nameEs:'Detener Tiempo', level:9, prepared:false, school:'transmutation', shape:'Self',
        desc:'1d4+1 turnos donde solo vos actuás. Termina si afectás otra criatura o un objeto cargado/llevado por otra.' },
      { name:'True Polymorph', nameEs:'Polimorfismo Verdadero', level:9, prepared:false, school:'transmutation', shape:'1 criatura/obj @ 30 ft · Concentración',
        desc:'Concentración, 1 h. Transformar criatura a otra criatura (cualquier CR) o objeto. Permanente si concentración completa.' }
    ]
  }
};
;
